<?php
$web_setting=array(
've_header' => array(
	'appearance'=>'type11',
	'logo_setting'=>'text',
	'logo'=>'',
	'logo_text'=>__('GoldenReality','cms_ve'),
	'logo_font'=>array(
		'font-size'=>'30',
		'font-family'=>'Ubuntu',
		'weight'=>'500',
		'color'=>'#b8a528',
	),
	'before_header'=>'',
	'background_color'=>array(
		'color1'=>'',
		'color2'=>'',
		'transparency'=>'100',
	),
	'background_image'=>array(
		'overlay_color'=>'#158ebf',
		'overlay_transparency'=>'80',
		'position'=>'center center',
		'repeat'=>'no-repeat',
		'image'=>'',
		'imageid'=>'',
	),
	'menu'=>$installed_menus['main'],
	'menu_font'=>array(
		'font-size'=>'16',
		'font-family'=>'Ubuntu',
		'weight'=>'300',
		'color'=>'#ffffff',
	),
	'menu_active_color'=>'#b8a528',
	'menu_submenu_text_color'=>'#ffffff',
	'menu_bg'=>array(
		'color1'=>'#ffffff',
		'color2'=>'',
	),
	'header_width'=>array(
		'size'=>'',
		'unit'=>'px',
	),
	'header_padding'=>'20',
	'background_color_fix'=>array(
		'color1'=>'',
		'color2'=>'',
		'transparency'=>'100',
	),
	'header_padding_fix'=>array(
		'size'=>'',
	),
),
        
've_footer' => array(
	'custom_footer'=>'',
	'appearance'=>'type1',
	'text'=>'',
	'menu'=>$installed_menus['main'],
	'background_color'=>array(
		'color1'=>'#07121c',
		'color2'=>'',
		'transparency'=>'100',
	),
	'background_image'=>array(
		'overlay_color'=>'#158ebf',
		'overlay_transparency'=>'80',
		'position'=>'center center',
		'repeat'=>'no-repeat',
		'image'=>'',
		'imageid'=>'',
	),
	'font'=>array(
		'font-size'=>'13',
		'font-family'=>'',
		'weight'=>'',
		'color'=>'#5f656b',
	),
	'footer_width'=>array(
		'size'=>'',
		'unit'=>'px',
	),
),
've_appearance' => array(
	'background_color'=>'#ffffff',
	'background_image'=>array(
		'cover'=>'cover',
    'fixed'=>'fixed',
		'color_filter'=>'color_filter',
		'overlay_color'=>'#051321',
		'overlay_transparency'=>'85',
		'position'=>'center bottom',
		'repeat'=>'no-repeat',
		'image'=>MW_IMAGE_LIBRARY.'webs/reality/house2.jpg',
		'imageid'=>'14',
		'pattern'=>'',
	),
	'font'=>array(
		'font-size'=>'15',
		'font-family'=>'Ubuntu',
		'weight'=>'400',
		'line-height'=>'',
		'color'=>'',
	),
	'link_color'=>'#b8a528',
	'title_font'=>array(
		'font-family'=>'Ubuntu',
		'weight'=>'500',
		'color'=>'',
	),
	'h1_font'=>array(
		'font-size'=>'30',
		'color'=>'',
	),
	'h2_font'=>array(
		'font-size'=>'23',
		'color'=>'',
	),
	'h3_font'=>array(
		'font-size'=>'18',
		'color'=>'',
	),
	'h4_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h5_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h6_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'li'=>'1',
),
'blog_sidebars' => array(
          	'sidebar_blog'=>$installed_sidebars['main'],
          	'sidebar_category'=>$installed_sidebars['main'],
          	'sidebar_post'=>$installed_sidebars['main'],
          	'sidebar_author'=>$installed_sidebars['main'],
          	'sidebar_tag'=>$installed_sidebars['main'],
          	'sidebar_search'=>$installed_sidebars['main'],
),    
 'blog_appearance' => array(
	'appearance'=>'style1',
	'structure'=>'right',
	'post_look'=>'1',
	'background_color'=>'#05192b',
	'background_image'=>array(
		'cover'=>'cover',
    'fixed'=>'fixed',
		'color_filter'=>'color_filter',
		'overlay_color'=>'#051321',
		'overlay_transparency'=>'85',
		'position'=>'center center',
		'repeat'=>'no-repeat',
		'image'=>MW_IMAGE_LIBRARY.'webs/reality/house2.jpg',
		'imageid'=>'14',
		'pattern'=>'',
	),
	'font'=>array(
		'font-size'=>'14',
		'font-family'=>'Arial',
		'weight'=>'normal',
		'line-height'=>'',
		'color'=>'#111111',
	),
	'link_color'=>'#b8a528',
	'title_font'=>array(
		'font-family'=>'Ubuntu',
		'weight'=>'500',
		'color'=>'',
	),
	'tb_background'=>array(
		'color1'=>'',
		'color2'=>'',
	),
	'tb_font'=>array(
		'font-size'=>'30',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'#ffffff',
	),
	'article_font'=>array(
		'font-size'=>'35',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'article_font_text'=>array(
		'font-size'=>'',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'sidebar_font'=>array(
		'font-size'=>'20',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'h1_font'=>array(
		'font-size'=>'30',
		'color'=>'',
	),
	'h2_font'=>array(
		'font-size'=>'23',
		'color'=>'',
	),
	'h3_font'=>array(
		'font-size'=>'18',
		'color'=>'',
	),
	'h4_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h5_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h6_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'li'=>'1',
),
'blog_footer' => array(
	'show'=>'global'
),
'blog_header' => array(
	'show'=>'global',
)
);
