<?php 
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#74848f',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#122530',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'50',
			'padding_left'=>array(
				'size'=>'60',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'60',
				'unit'=>'px',
			),
			'type'=>'basic',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Vložte svůj e-mail a získejte:','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">Lorem ipsum dolor sit amet set doma</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec varius sem vitae mauris aliquet, non porta orci blandit. Nam facilisis consequat leo non convallis.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'50',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'type'=>'smartemailing',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>'',
							'form-style'=>'2',
							'form-labels'=>'1',
							'form-look'=>'5',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button_text'=>'',
							'button'=>array(
								'style'=>'6',
								'font'=>array(
									'font-size'=>'28',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#1a1a1a',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup_type'=>'button',
							'image'=>'',
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'center',
						),
					),
					'4'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);

     
$config['setting']=array(
    've_popup'=>array(
        'width'=>array('size'=>'600','unit'=>'px'),
        'background'=>'#66727a'
    )
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();