<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#13181c',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'cover'=>'cover',
				'color_filter'=>'color_filter',
				'overlay_color'=>'#13181c',
				'overlay_transparency'=>'85',
				'position'=>'left top',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'bg/house_project.jpeg',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#b8b8b8',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('UKÁZKY MÝCH PRACÍ','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'60',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.1',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing <br />elit nec ipsum nec ligula.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'',
				'overlay_transparency'=>'90',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'1'=>array(
						'type'=>'catalog',
						'content'=>'',
						'style'=>array(
							'item_type'=>'own',
							'items'=>array(
								'0'=>array(
									'title'=>__('NÁZEV PROJEKTU','cms_ve'),
									'image'=>array(
										'image'=>'',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'',
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>__('NÁZEV PROJEKTU','cms_ve'),
									'image'=>array(
										'image'=>'',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'',
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>__('NÁZEV PROJEKTU','cms_ve'),
									'image'=>array(
										'image'=>'',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'',
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'page'=>'',
							'cols'=>'3',
							'style'=>'1',
							'text_align'=>'left',
							'font_title'=>array(
								'font-size'=>'',
							),
							'font_description'=>array(
								'font-size'=>'',
							),
							'font_color'=>'',
							'font_price'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'animation'=>'fade',
							'delay'=>'3500',
							'speed'=>'1000',
							'color_scheme'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Ukázky prací','cms_ve'),   
      'slug' => __('ukazky-praci','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
