<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'full_height'=>'full_height',
				'noheader'=>'noheader',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Děkuji vám!','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'80',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#fff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('E-book si můžete stáhnout zdarma níže.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'50',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'box',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'button',
									'content'=>__('Stáhnout e-book','cms_ve'),
									'style'=>array(
										'show'=>'url',
										'link'=>array(
											'link'=>'',
										),
										'popup'=>'',
										'align'=>'center',
										'button'=>array(
											'style'=>'11',
											'font'=>array(
												'font-size'=>'37',
												'font-family'=>'Open Sans',
												'weight'=>'700',
												'color'=>'#ffffff',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#cc1445',
												'color2'=>'',
											),
											'corner'=>'0',
											'height_padding'=>'0.7',
											'width_padding'=>'1.3',
											'border-color'=>'',
											'hover_color'=>array(
												'color1'=>'',
												'color2'=>'',
											),
											'hover_effect'=>'scale',
											'hover_font_color'=>'',
											'border_hover-color'=>'',
										),
										'show2'=>'url',
										'link2'=>array(
											'link'=>'',
										),
										'popup2'=>'',
										'button2'=>array(
											'style'=>'1',
											'font'=>array(
												'font-size'=>'30',
												'font-family'=>'',
												'weight'=>'',
												'color'=>'#2b2b2b',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffde21',
												'color2'=>'#ffcc00',
											),
											'corner'=>'8',
											'height_padding'=>'0.5',
											'width_padding'=>'1.2',
											'border-color'=>'',
											'hover_color'=>array(
												'color1'=>'',
												'color2'=>'',
											),
											'hover_effect'=>'',
											'hover_font_color'=>'',
											'border_hover-color'=>'',
										),
									),
								),
								'1'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">'.__('Klikni na tlačítko pro stažení e-booku.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'',
											'font-family'=>'',
											'weight'=>'',
											'line-height'=>'',
											'color'=>'',
										),
										'li'=>'',
										'style'=>'1',
										'p-background-color'=>array(
											'color1'=>'#e8e8e8',
											'color2'=>'',
											'transparency'=>'100',
										),
									),
								),
							),
						),
						'style'=>array(
							'background_color'=>array(
								'color1'=>'#ffffff',
								'color2'=>'',
								'transparency'=>'88',
							),
							'background_image'=>array(
								'position'=>'center center',
								'repeat'=>'no-repeat',
								'image'=>'',
								'pattern'=>'0',
							),
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'link-color'=>'',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'corner'=>'8',
							'padding'=>array(
								'top'=>'60',
								'bottom'=>'30',
								'left'=>'40',
								'right'=>'40',
							),
							'box-shadow'=>array(
								'horizontal'=>'0',
								'vertical'=>'0',
								'size'=>'0',
								'transparency'=>'10',
							),
							'title'=>'',
							'title-font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'title_bg'=>array(
								'color1'=>'#eeeeee',
								'color2'=>'',
								'transparency'=>'100',
							),
							'title_border'=>array(
								'size'=>'1',
								'color'=>'#dddddd',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);


$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();

$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_image'=>array('position'=>'center center','repeat'=>'no-repeat','cover'=>'cover', 'fixed'=>'fixed','image'=>MW_IMAGE_LIBRARY.'bg/reader.jpg','pattern'=>'0',)) 
);
