<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'cover'=>'cover',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'17',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'70',
			'padding_bottom'=>'20',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1>Lorem ipsum</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'47',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'3',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#121212',
								'color2'=>'',
								'transparency'=>'65',
							),
							'align'=>'left',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'45',
							'margin_bottom'=>'8',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<h1>curabitur eu lectus</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'47',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'3',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#121212',
								'color2'=>'',
								'transparency'=>'65',
							),
							'align'=>'left',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla. Curabitur lacinia venenatis neque non ornare. </p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'button',
						'content'=>__('Koupit','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'left',
							'button'=>array(
								'style'=>'6',
								'font'=>array(
									'font-size'=>'32',
									'font-family'=>'Bree Serif',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#08a174',
									'color2'=>'',
								),
								'hover_color'=>array(
									'color1'=>'#06946c',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'#ffffff',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'bounce',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>MW_IMAGE_LIBRARY.'book/book2.png',
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#08a174',
				'color2'=>'',
				'transparency'=>'85',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c5e0d8',
			),
			'link_color'=>'',
			'type'=>'fixed',
			'padding_top'=>'20',
			'padding_bottom'=>'20',
			'padding_left'=>array(
				'size'=>'20',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'30',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'40',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-five',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>get_template_url_image().'/modules/visualeditor/images/content/person.png',
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'center',
							'max-width'=>'150',
							'label'=>'',
							'style'=>'6',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-fourfive',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2>'.__('Jméno autora','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#121212',
								'color2'=>'',
								'transparency'=>'72',
							),
							'align'=>'left',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'12',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla. Curabitur lacinia venenatis neque non ornare. Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'20',
			'padding_bottom'=>'110',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Co se v knize dozvíte','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'4',
							'border'=>array(
								'size'=>'1',
								'color'=>'#ebebeb',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'90',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'cup',
										'size'=>'30',
										'color'=>'#ffffff',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'calendar-1',
										'size'=>'30',
										'color'=>'#ffffff',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'shop',
										'size'=>'30',
										'color'=>'#ffffff',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'3'=>array(
									'icon'=>array(
										'icon'=>'location-1',
										'size'=>'30',
										'color'=>'#ffffff',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'4'=>array(
									'icon'=>array(
										'icon'=>'pencil-1',
										'size'=>'30',
										'color'=>'#ffffff',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'5'=>array(
									'icon'=>array(
										'icon'=>'paper-plane',
										'size'=>'30',
										'color'=>'#ffffff',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
							),
							'cols'=>'two',
							'style'=>'5',
							'background-color'=>'#08a174',
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'2',
								'font'=>array(
									'font-size'=>'13',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#737373',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'corner'=>'90',
								'border-color'=>'#bdbdbd',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#08a174',
				'color2'=>'',
				'transparency'=>'90',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#b8d6cd',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'20',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Ukázka kapitoly z knihy','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'4',
							'border'=>array(
								'size'=>'1',
								'color'=>'#37b88b',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'70',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Zadejte svůj e-mail a my vám pošleme jednu kapitolu knihy zdarma ve formátu PDF.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'17',
						'style'=>array(
							'type'=>'custom',
							'html'=>'',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>'',
							'form-style'=>'2',
							'form-labels'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'20',
								'color'=>'',
							),
							'background'=>'#ffffff',
							'button_text'=>'',
							'button'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'25',
									'font-family'=>'Bree Serif',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_color'=>array(
									'color1'=>'#06946c',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'#ffffff',
							),
							'popup_type'=>'button',
							'image'=>'',
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'20',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Co o knize říkají','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'4',
							'border'=>array(
								'size'=>'1',
								'color'=>'#ebebeb',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'90',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Petra','cms_ve'),
									'company'=>__('Finanční poradce','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-w.jpg',
								),
								'1'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
                  'name'=>__('Honza','cms_ve'),
									'company'=>__('Informatik','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
								),
								'2'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Jana','cms_ve'),
									'company'=>__('Účetní','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-w2.jpg',
								),
							),
							'cols'=>'three',
							'style'=>'6',
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'5'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#08a174',
				'color2'=>'',
				'transparency'=>'90',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#b8d6cd',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'20',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Fakta o knize','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'4',
							'border'=>array(
								'size'=>'1',
								'color'=>'#37b88b',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'50',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'numbers',
						'content'=>'',
						'style'=>array(
							'numbers'=>array(
								'0'=>array(
									'type'=>'custom',
									'se'=>'1',
									'number'=>'128',
									'unit'=>'',
									'title'=>__('Stránek','cms_ve'),
								),
								'1'=>array(
									'type'=>'custom',
									'se'=>'1',
									'number'=>'4231',
									'unit'=>'',
									'title'=>__('Čtenářů','cms_ve'),
								),
								'2'=>array(
									'type'=>'custom',
									'se'=>'1',
									'number'=>'2300',
									'unit'=>'',
									'title'=>__('Fanoušků','cms_ve'),
								),
							),
							'style'=>'1',
							'cols'=>'three',
							'number_font'=>array(
								'font-size'=>'60',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
							),
							'text_font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'6'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eget sem vitae neque placerat mattis.</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'button',
						'content'=>__('Koupit','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'37',
									'font-family'=>'Bree Serif',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#08a174',
									'color2'=>'',
								),
								'hover_color'=>array(
									'color1'=>'#06946c',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'#ffffff',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'bounce',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);$config['setting']=array ( 
	've_header' => array(
		'show'=>'page',
		'appearance'=>'type1',
		'logo'=>get_template_url_image().'/modules/visualeditor/images/default/logo2.png',
		'background_color'=>array(
			'color1'=>'#08a174',
			'color2'=>'',
			'transparency'=>'90',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
		),
		'menu'=>'',
		'menu_font'=>array(
			'font-size'=>'16',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#c9f0e6',
		),
		'menu_active_color'=>'#ffffff',
		'menu_bg'=>array(
			'color1'=>'#121212',
			'color2'=>'',
		),
		'header_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),

	've_footer' => array(
		'show'=>'page',
		'custom_footer'=>'',
		'appearance'=>'type1',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'#000000',
			'color2'=>'',
			'transparency'=>'89',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
		),
		'font'=>array(
			'font-size'=>'13',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#7a7a7a',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),
 
	've_appearance' => array(
		'page_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
		'background_color'=>'#08a174',
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'repeat',
			'fixed'=>'fixed',
			'cover'=>'cover',
			'image'=>MW_IMAGE_LIBRARY.'bg/bg_forest.jpg',
			'pattern'=>'0',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'',
			'weight'=>'',
			'line-height'=>'',
			'color'=>'',
		),
		'link_color'=>'',
		'title_font'=>array(
			'font-family'=>'Bree Serif',
			'weight'=>'400',
			'color'=>'',
		),
		'h1_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h2_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h3_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h4_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h5_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h6_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'li'=>'',
	),

);
$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();
