<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c4d8e6',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#0b5c91',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'25',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Přihláška','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-threefour',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'bullets',
						'content'=>'',
						'style'=>array(
							'bullets'=>array(
								'0'=>array(
									'title'=>'Lorem ipsum dolor',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.',
								),
								'1'=>array(
									'title'=>'Sed pulvinar lacus ',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.',
								),
								'2'=>array(
									'title'=>'Proin dui lacus',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. Proin dui lacus, aliquet ut tellus porta, ullamcorper rutrum nisl.',
								),
							),
							'type'=>'decimal',
							'style_decimal'=>'1',
							'start_number'=>'1',
							'style_image'=>'1',
							'icon'=>'1',
							'bullet_color'=>'#0b5c91',
							'custom_image'=>'',
						),
					),
					'1'=>array(
						'type'=>'fapi',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'background-color'=>'#ffffff',
							'font_title'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'14',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#0b5c91',
									'color2'=>'#044570',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-four',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'graphic',
						'content'=>'',
						'style'=>array(
							'style'=>array(
								'item'=>'guarantee6',
								'itemtype'=>'img',
							),
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'0',
						),
					),
					'3'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. ',
									'name'=>__('Jan Novák','cms_ve'),
									'company'=>__('Grafik','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
								),
								'1'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In erat velit, tristique et erat et, eleifend pulvinar lectus. Sed pulvinar lacus nec libero luctus tincidunt. ',
									'name'=>__('Jan Novák','cms_ve'),
									'company'=>__('Grafik','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
								),
							),
							'cols'=>'one',
							'style'=>'1',
							'font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#dbdbdb',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#262626',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Potřebujete pomoc?','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<div><p style="text-align: center;">'.__('Napište mi na <a href="">mujmail@seznam.cz</a> nebo volejte na 123 456 789.','cms_ve').'</p><p style="text-align: center;">'.__('Jsme tu pro vás, rádi vám pomůžeme.','cms_ve').'</p></div>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array (  
 've_header' => array(),
 've_footer' => array(), 
 've_appearance' => array() 
);
$config['config']=array();
