<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#007ab3',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'30',
			'padding_bottom'=>'20',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Nadpis stránky','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'#c4d8e6',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'normal',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'50',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2>'.__('Obsah je vždy lepší strukturovat pomocí různých elementů než jej vytvářet celý pomocí jednoho textového elementu.','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc volutpat ante pharetra leo sagittis iaculis. Vestibulum ornare ante a libero congue ullamcorper. Ut viverra odio quis cursus commodo. Sed malesuada euismod ante vel semper. Duis vitae molestie nunc. Cras euismod nunc sed neque posuere, quis convallis massa cursus. Vivamus congue lectus tellus, non rhoncus ligula tristique sed. Nullam scelerisque, diam at posuere laoreet, sapien libero dapibus metus, egestas iaculis lorem metus sit amet eros. Donec viverra enim ac malesuada molestie.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'',
							),
							'li'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<h2>'.__('Máte tak lepší kontrolu nad obsahem.','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc volutpat ante pharetra leo sagittis iaculis. Vestibulum ornare ante a libero congue ullamcorper. Ut viverra odio quis cursus commodo. Sed malesuada euismod ante vel semper.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'',
							),
							'li'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
					'4'=>array(
						'type'=>'bullets',
						'content'=>'',
						'style'=>array(
							'bullets'=>array(
								'0'=>array(
									'title'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc volutpat ante pharetra leo sagittis iaculis. Vestibulum ornare ante a libero congue ullamcorper. Ut viverra odio quis cursus commodo. ',
								),
								'1'=>array(
									'title'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc volutpat ante pharetra leo sagittis iaculis. Vestibulum ornare ante a libero congue ullamcorper. Ut viverra odio quis cursus commodo. ',
								),
								'2'=>array(
									'title'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc volutpat ante pharetra leo sagittis iaculis. Vestibulum ornare ante a libero congue ullamcorper. Ut viverra odio quis cursus commodo. ',
								),
							),
							'type'=>'decimal',
							'style_decimal'=>'2',
							'start_number'=>'1',
							'style_image'=>'1',
							'icon'=>'1',
							'bullet_color'=>'#007ab3',
							'custom_image'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array();
$config['config']=array(
  'body_class'=>'fixed_width_page'
);