<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#000000',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'cover'=>'cover',
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'left top',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'webs/reality/businessman.jpg',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'50',
			'padding_bottom'=>'50',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
				'full_height'=>'full_height',
				'noheader'=>'noheader',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('<p>Bezpečně vás provedu</p>
<p>při <strong>prodeji</strong> či <strong>pronájmu</strong></p>
<p>vaší nemovitosti</p>','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'53',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.3',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'button',
						'content'=>__('Moje nabídka','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'page'=>$installed_pages['offer'],
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'left',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'Open Sans',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#6babe0',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'1',
								'width_padding'=>'1.4',
								'border-color'=>'#2b2b2b',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'hover_font_color'=>'#000000',
								'border_hover-color'=>'',
							),
							'show_but2'=>'1',
							'text2'=>__('Moje služby','cms_ve'),
							'show2'=>'url',
							'link2'=>array(
								'page'=>$installed_pages['servis'],
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'Open Sans',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.9',
								'width_padding'=>'1.4',
								'border-color'=>'#ffffff',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'hover_font_color'=>'#000000',
								'border_hover-color'=>'#ffffff',
							),
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#6babe0',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c3d4e3',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'60',
			'padding_bottom'=>'60',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'#6b6b6b',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'#dbdbdb',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>MW_IMAGE_LIBRARY.'book/ebook-cover.png',
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
						'config'=>array(
							'max_width'=>'200',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: left;">'.__('Stáhněte si zdarma ebook','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'10',
							'margin_bottom'=>'5',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">'.__('5 největších chyb, které dělají prodejci nemovitostí','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'type'=>'smartemailing',
							'html'=>'',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>array(
								'page'=>'',
								'link'=>'',
							),
							'url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'20',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'popup'=>'1',
							'popup_title'=>__('Zadejte e-mail, na který vám máme e-book poslat','cms_ve'),
							'popup_type'=>'button',
							'image'=>'',
							'popup_text'=>__('Stáhnout e-book','cms_ve'),
							'popupbutton'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'18',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.4',
								'border-color'=>'#ffffff',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#fcf9f9',
									'color2'=>'',
								),
								'hover_font_color'=>'#6babe0',
								'border_hover-color'=>'',
							),
							'link_text'=>__('Registrovat se','cms_ve'),
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'left',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_slides'=>array(
				'0'=>array(
					'image'=>array(
						'image'=>'',
						'imageid'=>'',
					),
				),
			),
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Moje služby','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'80',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'home',
										'size'=>'50',
										'color'=>'#6babe0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Prodej a pronájm nemovitostí','cms_ve'),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. ',
									'button_text'=>__('Více o službě →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'money-1',
										'size'=>'50',
										'color'=>'#6babe0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Zajišťuji výkup nemovitostí','cms_ve'),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. ',
									'button_text'=>__('Více o službě →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'chart-bar-1',
										'size'=>'50',
										'color'=>'#6babe0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Profesionální marketing','cms_ve'),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. ',
									'button_text'=>__('Více o službě →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'three',
							'style'=>'1',
							'background-color'=>'#6babe0',
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'2',
								'font'=>array(
									'font-size'=>'13',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#737373',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'90',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#e8e9eb',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_slides'=>array(
				'0'=>array(
					'image'=>array(
						'image'=>'',
						'imageid'=>'',
					),
				),
			),
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Moje nabídka','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'80',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'catalog',
						'content'=>'',
						'style'=>array(
							'item_type'=>'own',
							'items'=>array(
								'0'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house1.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house2.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'3'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house4.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'4'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house5.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'5'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house1.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
							),
							'page'=>'',
							'cols'=>'3',
							'style'=>'3',
							'font_color'=>'',
							'font_title'=>array(
								'font-size'=>'20',
							),
							'font_description'=>array(
								'font-size'=>'',
							),
							'font_price'=>array(
								'font-size'=>'16',
								'color'=>'#d15151',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'70',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'button',
						'content'=>__('Celá nabídka','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'page'=>$installed_pages['offer'],
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'Open Sans',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#6babe0',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'1',
								'width_padding'=>'1.4',
								'border-color'=>'#2b2b2b',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#000000',
									'color2'=>'',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'text2'=>'Moje služby',
							'show2'=>'url',
							'link2'=>array(
								'page'=>'',
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#929394',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.9',
								'width_padding'=>'1.4',
								'border-color'=>'#626263',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'hover_font_color'=>'#000000',
								'border_hover-color'=>'#ffffff',
							),
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#000000',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_slides'=>array(
				'0'=>array(
					'image'=>array(
						'image'=>'',
						'imageid'=>'',
					),
				),
				'1'=>array(
					'image'=>array(
						'image'=>'',
						'imageid'=>'',
					),
				),
				'2'=>array(
					'image'=>array(
						'image'=>'',
						'imageid'=>'',
					),
				),
			),
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#969494',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'numbers',
						'content'=>'',
						'style'=>array(
							'numbers'=>array(
								'0'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'29',
									),
									'number'=>'1832',
									'unit'=>'',
									'title'=>__('spokojených zákazníků','cms_ve'),
								),
								'1'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'29',
									),
									'number'=>'27',
									'unit'=>'',
									'title'=>__('let zkušeností','cms_ve'),
								),
								'2'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'29',
									),
									'number'=>'7254',
									'unit'=>'',
									'title'=>__('prodejů','cms_ve'),
								),
							),
							'style'=>'1',
							'cols'=>'three',
							'number_font'=>array(
								'font-size'=>'60',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#fcf9f9',
							),
							'text_font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'5'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_slides'=>array(
				'0'=>array(
					'image'=>array(
						'image'=>'',
						'imageid'=>'',
					),
				),
			),
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Reference','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'80',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Petra','cms_ve'),
									'company'=>__('Finanční poradce','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/face-w.jpg',
										'imageid'=>'',
									),
								),
								'1'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Honza','cms_ve'),
									'company'=>__('Informatik','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
										'imageid'=>'',
									),
								),
								'2'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Jana','cms_ve'),
									'company'=>__('Účetní','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/face-w2.jpg',
										'imageid'=>'',
									),
								),
							),
							'cols'=>'three',
							'style'=>'7',
							'font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font-author'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'animation'=>'fade',
							'delay'=>'3500',
							'speed'=>'1000',
							'color_scheme'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'6'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#000000',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'cover'=>'cover',
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'right top',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'webs/reality/businessman2.jpg',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c7c5c5',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'140',
			'padding_bottom'=>'140',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">'.__('Něco o mně','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#fcf9f9',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis nibh consequat, feugiat urna et, consectetur justo. Suspendisse potenti. Vivamus feugiat, nunc ut elementum hendrerit, nunc ex finibus augue, eu venenatis nunc orci id augue. Nulla tempor erat urna, id dignissim enim congue at. Etiam dapibus interdum odio a gravida. Donec risus purus, pellentesque a lacus vel, imperdiet mollis augue. Sed dapibus dolor...</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('Více o mně','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'page'=>$installed_pages['story'],
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'left',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'Open Sans',
									'weight'=>'400',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#6babe0',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.4',
								'border-color'=>'#2b2b2b',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#fcf9f9',
									'color2'=>'',
								),
								'hover_font_color'=>'#000000',
								'border_hover-color'=>'',
							),
							'text2'=>__('Moje služby','cms_ve'),
							'show2'=>'url',
							'link2'=>array(
								'page'=>'',
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#929394',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.9',
								'width_padding'=>'1.4',
								'border-color'=>'#626263',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'hover_font_color'=>'#000000',
								'border_hover-color'=>'#ffffff',
							),
						),
					),
				),
			),
		),
	),
	'7'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#6babe0',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c3d4e3',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'60',
			'padding_bottom'=>'60',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'#6b6b6b',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'#dbdbdb',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>MW_IMAGE_LIBRARY.'book/ebook-cover.png',
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
						'config'=>array(
							'max_width'=>'200',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: left;">'.__('Stáhněte si zdarma ebook','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'10',
							'margin_bottom'=>'5',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">'.__('5 největších chyb, které dělají prodejci nemovitostí','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'type'=>'smartemailing',
							'html'=>'',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>array(
								'page'=>'',
								'link'=>'',
							),
							'url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'20',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'popup'=>'1',
							'popup_title'=>__('Zadejte e-mail, na který vám máme e-book poslat','cms_ve'),
							'popup_type'=>'button',
							'image'=>'',
							'popup_text'=>__('Stáhnout e-book','cms_ve'),
							'popupbutton'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'18',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.4',
								'border-color'=>'#ffffff',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'#fcf9f9',
									'color2'=>'',
								),
								'hover_font_color'=>'#6babe0',
								'border_hover-color'=>'',
							),
							'link_text'=>__('Registrovat se','cms_ve'),
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'left',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Úvod','cms_ve'),   
      'slug' => __('home','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
