<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#000000',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#e0e0e0',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Nabídka','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'catalog',
						'content'=>'',
						'style'=>array(
							'item_type'=>'own',
							'items'=>array(
								'0'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house1.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house2.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'3'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house4.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'4'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house5.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
								'5'=>array(
									'title'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'webs/reality/house1.jpg',
										'imageid'=>'',
									),
									'description'=>'',
									'price'=>__('1 250 000 Kč','cms_ve'),
									'link'=>array(
										'page'=>$installed_pages['product'],
										'link'=>'',
									),
								),
							),
							'page'=>'',
							'cols'=>'3',
							'style'=>'3',
							'font_color'=>'',
							'font_title'=>array(
								'font-size'=>'20',
							),
							'font_description'=>array(
								'font-size'=>'',
							),
							'font_price'=>array(
								'font-size'=>'16',
								'color'=>'#d15151',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Nabídka','cms_ve'),   
      'slug' => __('nabidka','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
