<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'13',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#ededed',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Zveme vás na webinář na téma:','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, ectetur elit. <span style="color: #e65c25;">Donec ornare</span> non.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'48',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'setting'=>array(
								'share'=>'share',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'50',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Co vám přinese tento živý webinář?','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Aliquam a mauris sodales, interdum felis nec, blandit metus. Quisque tortor augue, imperdiet nec fringilla ac, mollis aliquam magna. Vivamus ut sem ut dolor dictum posuere. Curabitur quis convallis arcu.</p>
<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
<li>Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam.</li>
</ul>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'41',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>__('Webinář doprovází a otázky klade Jan Novák.','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'box',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'title',
									'content'=>'<p style="text-align: center;">'.__('Webinář začíná za:','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'26',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'',
											'text-shadow'=>'none',
										),
									),
									'config'=>array(
										'max_width'=>'',
										'margin_top'=>'0',
										'margin_bottom'=>'15',
										'delay'=>'',
										'class'=>'',
									),
								),
								'1'=>array(
									'type'=>'countdown',
									'content'=>array(
										'date'=>'00000',
										'hour'=>'0',
										'minute'=>'0',
									),
									'style'=>array(
										'evergreen_days'=>'',
										'redirect'=>array(
											'link'=>'',
										),
										'style'=>'6',
										'background-color'=>'',
										'font'=>array(
											'font-size'=>'33',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'',
										),
										'font-text'=>array(
											'color'=>'',
										),
									),
								),
								'2'=>array(
									'type'=>'title',
									'content'=>'<p style="text-align: center;"><span style="text-decoration: underline;">'.__('Pátek 24. 5. ve 13.00 hodin','cms_ve').'</span></p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'14',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'',
											'text-shadow'=>'none',
										),
									),
									'config'=>array(
										'max_width'=>'',
										'margin_top'=>'0',
										'margin_bottom'=>'40',
										'delay'=>'',
										'class'=>'',
									),
								),
								'3'=>array(
									'type'=>'title',
									'content'=>'<p style="text-align: center;">'.__('Rezervujte si své místo.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'20',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'',
											'text-shadow'=>'none',
										),
									),
									'config'=>array(
										'max_width'=>'',
										'margin_top'=>'0',
										'margin_bottom'=>'20',
										'delay'=>'',
										'class'=>'',
									),
								),
								'4'=>array(
									'type'=>'seform',
									'content'=>'',
									'style'=>array(
										'form-style'=>'1',
										'form-look'=>'3',
										'form-font'=>array(
											'font-size'=>'18',
											'color'=>'',
										),
										'background'=>'#ffffff',
										'button_text'=>'',
										'button'=>array(
											'style'=>'1',
											'font'=>array(
												'font-size'=>'26',
												'font-family'=>'Open Sans',
												'weight'=>'600',
												'color'=>'#ffffff',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#e66c25',
												'color2'=>'#e65c25',
											),
											'corner'=>'0',
											'border-color'=>'',
										),
										'popup_text'=>__('Registrovat se na webinář','cms_ve'),
										'popup_title'=>__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve'),
										'popupbutton'=>array(
											'style'=>'9',
											'font'=>array(
												'font-size'=>'40',
												'font-family'=>'Open Sans',
												'weight'=>'600',
												'color'=>'#2b2b2b',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffde21',
												'color2'=>'#ffcc00',
											),
											'corner'=>'5',
											'border-color'=>'',
										),
										'align'=>'center',
										'link_font'=>array(
											'font-size'=>'',
											'color'=>'',
										),
									),
								),
								'5'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">'.__('POZOR: Místa pro vysílání mohou být omezena, proto si je raději rezervujte a přijďte včas, prosím.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'12',
											'font-family'=>'',
											'weight'=>'',
											'line-height'=>'',
											'color'=>'#eb2323',
										),
										'li'=>'',
										'style'=>'1',
										'p-background-color'=>array(
											'color1'=>'#e8e8e8',
											'color2'=>'',
											'transparency'=>'100',
										),
									),
								),
							),
						),
						'style'=>array(
							'background_color'=>array(
								'color1'=>'#eeeeee',
								'color2'=>'',
								'transparency'=>'100',
							),
							'background_image'=>array(
								'position'=>'center center',
								'repeat'=>'no-repeat',
								'image'=>'',
								'imageid'=>'',
								'pattern'=>'',
							),
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'link-color'=>'',
							'border'=>array(
								'size'=>'2',
								'color'=>'#ededed',
							),
							'corner'=>'0',
							'padding'=>array(
								'top'=>'40',
								'bottom'=>'30',
								'left'=>'40',
								'right'=>'40',
							),
							'box-shadow'=>array(
								'horizontal'=>'0',
								'vertical'=>'0',
								'size'=>'0',
								'transparency'=>'10',
							),
							'title'=>'',
							'title-font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'title_bg'=>array(
								'color1'=>'#eeeeee',
								'color2'=>'',
								'transparency'=>'100',
							),
							'title_border'=>array(
								'size'=>'0',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'13',
			),
			'border-top'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#ededed',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Rezervujte si své místo.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'27',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#ffffff',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'26',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#e66c25',
									'color2'=>'#e65c25',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Registrovat se na webinář','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'40',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#e66c25',
									'color2'=>'#e65c25',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('POZOR: Místa pro vysílání mohou být omezena, proto si je raději rezervujte a přijďte včas, prosím.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'12',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#eb2323',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));

$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_color'=>'#ffffff') 
);
$config['config']=array(
  'styles'=>true,
);