<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'cover'=>'cover',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'200',
			'padding_bottom'=>'200',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('JIŽ BRZY WEB SPUSTÍME','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Chcete být mezi prvními, kdo se o spuštění dozví? Vyplňte formulář níže a my vám dáme vědět.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'16',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'500',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'17',
						'style'=>array(
							'type'=>'custom',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#ffffff',
							'button_text'=>'',
							'button'=>array(
								'style'=>'6',
								'font'=>array(
									'font-size'=>'25',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#c20e0e',
									'color2'=>'#9e0c0c',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('ZJISTIT VÍCE','cms_ve'),
							'popup_title'=>__('Vložte svůj e-mail a my vás budeme informovat o průběhu.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'35',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#c20e0e',
									'color2'=>'#9e0c0c',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'70',
			'padding_bottom'=>'70',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('CO NABÍZÍME','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'rocket',
										'size'=>'50',
										'color'=>'#c20e0e',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. ',
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'lightbulb-1',
										'size'=>'50',
										'color'=>'#c20e0e',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. ',
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'gift',
										'size'=>'50',
										'color'=>'#c20e0e',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. ',
								),
							),
							'cols'=>'three',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#a1a1a1',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#1a1a1a',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'80',
			'padding_bottom'=>'60',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image_text',
						'content'=>'<div class="element_content">
<div class="in_element_content entry_content element_text_size_small element_text_li">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit. Duis ut ante vestibulum, varius neque nec, mollis eros. Integer scelerisque ante et vestibulum tincidunt. Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. Pellentesque suscipit aliquam tincidunt. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna in sed dolor. </p>
</div>
</div>',
						'style'=>array(
							'title'=>__('Něco o projektu','cms_ve'),
							'image'=>'',
							'style'=>'1',
							'align'=>'left',
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
							),
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Nadpis, klidně na dva tři řádky, který přiměje <br />návštěvníka, aby vám dal svůj kontakt.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'28',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'seform',
						'content'=>'17',
						'style'=>array(
							'type'=>'custom',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#ffffff',
							'button_text'=>'',
							'button'=>array(
								'style'=>'6',
								'font'=>array(
									'font-size'=>'25',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#c20e0e',
									'color2'=>'#9e0c0c',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('ZJISTIT VÍCE','cms_ve'),
							'popup_title'=>__('Vložte svůj e-mail a my vás budeme informovat o průběhu.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'26',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#c20e0e',
									'color2'=>'#9e0c0c',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array ( 
 've_header' => array('show' => 'page','appearance'=>'type11', 'logo' =>  get_template_url_image().'/modules/visualeditor/images/default/logo2.png', 'background_color'=>array('color1'=>'','color2'=>''),'menu_font'=>array('font-size'=>'14','font-family'=>'','weight'=>'','color'=>'#e6e6e6'),'menu_active_color'=>'#158ebf'),
 've_footer' => array('show' => 'page', 'appearance'=>'type1', 'background_color'=>array('color1'=>'#242424','color2'=>''),'font'=>array('font-family'=>'','weight'=>'','color'=>'#a8a8a8')), 
 've_appearance' => array('background_image' => array('position' => 'center center', 'repeat' => 'no-repeat', 'cover' => 'cover', 'fixed' => 'fixed', 'image' =>  get_template_url_image().'/modules/visualeditor/templates/images/background1.jpg'))
);
$config['config']=array();
