<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'14',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'45',
			'padding_bottom'=>'35',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">Lorem ipsum dolor sit amet set doma</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'align'=>'center',
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit. Duis ut ante vestibulum, varius neque nec, mollis eros. Integer scelerisque ante et vestibulum tincidunt. Curabitur vel mi a odio dignissim.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#f7f7f7',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'28',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#d60424',
									'color2'=>'#c7001e',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Chci vědět víc','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a registrujte se.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'8',
								'font'=>array(
									'font-size'=>'32',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#d60424',
									'color2'=>'#c7001e',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
					),
					'4'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit. </p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'11',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#8f8f8f',
							),
							'li'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array (  
 've_header' => array('show' => 'page', 'appearance'=>'type11', 'logo' =>  get_template_url_image().'/modules/visualeditor/images/default/logo2.png', 'background_color'=>array('color1'=>'','color2'=>''), 'menu_font'=>array('font-family'=>''), 'menu'=>''),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_image' => array('pattern' => '19', 'image' =>  ''),'background_color'=>'#3d3d3d') 
);
$config['config']=array(
  'styles'=>true,
  'hide_rows'=>true,
  'body_class'=>'fixed_template'
);