<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'Verdana',
				'weight'=>'normal',
				'color'=>'#d7eef5',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#6eb7cf',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'20',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'video',
						'content'=>'',
						'style'=>array(
							'code'=>'',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'standard',
							'scheme'=>'light',
							'setting'=>array(
								'faces'=>'faces',
								'share'=>'share',
							),
							'align'=>'left',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 id="watch-headline-title">Lorem ipsum dolor sit amet son</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget tempor nisi. Integer est nunc dolor sit amet</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'Roboto Condensed',
								'weight'=>'300',
								'color'=>'',
							),
							'li'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'20',
								'color'=>'',
							),
							'background'=>'#ffffff',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'Open Sans Condensed',
									'weight'=>'700',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#fac000',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'70',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Co se v programu dozvíte?','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'50',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'desktop',
										'size'=>'30',
										'color'=>'',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'music',
										'size'=>'30',
										'color'=>'',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'shop',
										'size'=>'30',
										'color'=>'',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
								),
								'3'=>array(
									'icon'=>array(
										'icon'=>'globe',
										'size'=>'30',
										'color'=>'',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
								),
								'4'=>array(
									'icon'=>array(
										'icon'=>'food',
										'size'=>'30',
										'color'=>'',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
								),
								'5'=>array(
									'icon'=>array(
										'icon'=>'paper-plane',
										'size'=>'30',
										'color'=>'',
									),
									'title'=>'Vivamus vulputate',
									'text'=>'In sit amet dui nec orci pretium dictum. Vivamus vulputate adiping sapien, et dapibus dolor . ',
								),
							),
							'cols'=>'two',
							'style'=>'4',
							'background-color'=>'#6eb7cf',
							'font'=>array(
								'font-size'=>'23',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array(
've_appearance' => array('title_font'=>array('font-family'=>'Open Sans Condensed','weight'=>'700','color'=>'')) 
);

$config['config']=array();
