<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c3cbcf',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'90',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
				'full_height'=>'full_height',
				'noheader'=>'noheader',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Dům 6+kk s garáží','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'animate'=>'fadeInUp',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ac dolor at leo feugiat convallis. Donec congue porttitor scelerisque.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('12 500 000 Kč','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#ffffff',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'300',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
								'imageid'=>'',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
					'1'=>array(
						'type'=>'image_gallery',
						'content'=>'',
						'style'=>array(
							'image_gallery_items'=>array(
								'0'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
								'1'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
								'2'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
								'3'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
							),
							'cols'=>'3',
							'gallery_style'=>'no_captions',
							'thumb_name'=>'mio_columns_',
							'font'=>array(
								'font-size'=>'16',
								'font-family'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'animation'=>'fade',
							'delay'=>'3500',
							'speed'=>'1000',
							'color_scheme'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec venenatis est, nec ullamcorper mauris. Nullam tincidunt tortor at convallis dictum. In congue egestas porta. Aliquam blandit ornare sem, eget vulputate ante facilisis vitae. Aliquam vitae ex turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec venenatis est, nec ullamcorper mauris. Nullam tincidunt tortor at convallis dictum. In congue egestas porta. Aliquam blandit ornare sem, eget vulputate ante facilisis vitae. Aliquam vitae ex turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec venenatis est, nec ullamcorper mauris. Nullam tincidunt tortor at convallis dictum. In congue egestas porta. Aliquam blandit ornare sem, eget vulputate ante facilisis vitae. Aliquam vitae ex turpis.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'table',
						'content'=>'',
						'style'=>array(
							'lines'=>array(
								'0'=>array(
									'title'=>__('Dispozice','cms_ve'),
									'text'=>__('6+kk','cms_ve'),
								),
								'1'=>array(
									'title'=>__('Energetický štítek','cms_ve'),
									'text'=>'B',
								),
								'2'=>array(
									'title'=>__('Užitná plocha','cms_ve'),
									'text'=>__('65 m2','cms_ve'),
								),
								'3'=>array(
									'title'=>__('Rok výstavby','cms_ve'),
									'text'=>'2014',
								),
							),
							'width'=>array(
								'size'=>'150',
								'unit'=>'px',
							),
							'style'=>'2',
							'font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c3cbcf',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Poslat dotaz','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#fcf9f9',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ac dolor at leo feugiat convallis. Donec congue porttitor scelerisque.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'contactform',
						'content'=>'',
						'style'=>array(
							'email'=>'@',
							'button_text'=>__('Odeslat dotaz','cms_ve'),
							'hide'=>array(
								'is_saved'=>'1',
							),
							'form-appearance'=>'1',
							'form-style'=>'3',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'20',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#b8a528',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.9',
								'width_padding'=>'1.5',
								'border-color'=>'',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
				),
			),
		),
	),
);
$setting=array ( 
	've_appearance' => array(
		'background_color'=>'',
		'background_setting'=>'image',
		'background_image'=>array(
			'cover'=>'cover',
			'color_filter'=>'color_filter',
			'overlay_color'=>'#051321',
			'overlay_transparency'=>'85',
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>MW_IMAGE_LIBRARY.'webs/reality/house3.jpg',
			'imageid'=>'',
			'pattern'=>'',
		),
	),

);

$page=array(
  'page'=>array(      
      'title' => __('Nemovitost','cms_ve'),   
      'slug' => __('nemovitost','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>$setting,
  'layer'=>base64_encode(serialize($temp_layer)),
);
