<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'150',
			'padding_bottom'=>'150',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
				'full_height'=>'full_height',
				'noheader'=>'noheader',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Děkujeme!','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'70',
								'font-family'=>'Ubuntu',
								'weight'=>'300',
								'line-height'=>'1.6',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'fadeInUp',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('Zpět na hlavní stranu','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'20',
									'font-family'=>'Ubuntu',
									'weight'=>'500',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#b8a528',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.5',
								'border-color'=>'#90d325',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'hover_font_color'=>'#90d325',
								'border_hover-color'=>'#90d325',
							),
							'text2'=>__('Chci prodat nemovitost','cms_ve'),
							'show2'=>'url',
							'link2'=>array(
								'page'=>'',
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'3',
								'font'=>array(
									'font-size'=>'25',
									'font-family'=>'Ubuntu',
									'weight'=>'300',
									'color'=>'#90d325',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'#90d325',
								'hover_effect'=>'scale',
								'hover_color'=>array(
									'color1'=>'#90d325',
									'color2'=>'',
								),
								'hover_font_color'=>'#ffffff',
								'border_hover-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Poděkování','cms_ve'),   
      'slug' => __('podekovani','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (
      've_header' => array('show'=>'noheader'),
      've_footer' => array('show'=>'nofooter'),
  ),
  'layer'=>base64_encode(serialize($temp_layer)),
);
