<?php
$web_setting=array(
've_header' => array(
	'logo_setting'=>'text',
	'logo'=>'',
	'logo_size'=>'',
	'logo_text'=>'Lektorka',
	'logo_font'=>array(
		'font-size'=>'22',
		'font-family'=>'Merriweather',
		'weight'=>'400',
		'color'=>'#3d3d3d',
	),
	'menu'=>$installed_menus['main'],
	'background_color'=>array(
		'color1'=>'#ffffff',
		'color2'=>'',
		'transparency'=>'100',
	),
	'appearance'=>'type1',
	'menu_font'=>array(
		'font-size'=>'15',
		'font-family'=>'Merriweather',
		'weight'=>'400',
		'color'=>'#3d3d3d',
	),
	'menu_active_color'=>'#d67cb8',
	'menu_submenu_text_color'=>'#ffffff',
	'menu_bg'=>array(
		'color1'=>'#121212',
		'color2'=>'',
	),
	'before_header'=>'',
	'background_image'=>array(
		'position'=>'center center',
		'repeat'=>'no-repeat',
		'image'=>'',
		'imageid'=>'',
	),
	'header_width'=>array(
		'size'=>'',
		'unit'=>'px',
	),
	'header_padding'=>'20',
	'background_color_fix'=>array(
		'color1'=>'#ffffff',
		'color2'=>'',
		'transparency'=>'100',
	),
	'header_padding_fix'=>array(
		'size'=>'20',
	),
	'header_shadow_fix'=>'1',
),

've_footer' => array(
		'custom_footer'=>'',
		'appearance'=>'type2',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'#ffffff',
			'color2'=>'',
			'transparency'=>'100',
		),
		'background_image'=>array(
			'overlay_color'=>'#158ebf',
			'overlay_transparency'=>'80',
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#999999',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
),
 
've_appearance' => array(
		'background_color'=>'#ffffff',
		'background_image'=>array(
			'cover'=>'cover',
			'overlay_color'=>'#158ebf',
			'overlay_transparency'=>'80',
			'position'=>'center top',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
			'pattern'=>'',
		),
		'title_font'=>array(
			'font-family'=>'Merriweather',
			'weight'=>'400',
			'color'=>'#3d3d3d',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'Open Sans',
			'weight'=>'400',
			'line-height'=>'1.8',
			'color'=>'#3d3d3d',
		),
		'link_color'=>'#d67cb8',
		'h1_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h2_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h3_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h4_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h5_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h6_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'li'=>'',
),
  
'blog_sidebars' => array(
          	'sidebar_blog'=>$installed_sidebars['main'],
          	'sidebar_category'=>$installed_sidebars['main'],
          	'sidebar_post'=>$installed_sidebars['main'],
          	'sidebar_author'=>$installed_sidebars['main'],
          	'sidebar_tag'=>$installed_sidebars['main'],
          	'sidebar_search'=>$installed_sidebars['main'],
),    
'blog_appearance' => array(
	'appearance'=>'style4',
	'background_color'=>'#ffffff',
	'background_image'=>array(
		'overlay_color'=>'#158ebf',
		'overlay_transparency'=>'80',
		'position'=>'center center',
		'repeat'=>'no-repeat',
		'image'=>'',
		'imageid'=>'',
		'pattern'=>'',
	),
	'structure'=>'right',
	'sidebar_font'=>array(
		'font-size'=>'20',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'tb_background'=>array(
		'color1'=>'#dadadc',
		'color2'=>'',
	),
	'tb_font'=>array(
		'font-size'=>'45',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'#111111',
	),
	'post_look'=>'1',
	'excerpt_length'=>array(
		'size'=>'',
	),
	'button_color'=>'#209bce',
	'article_font'=>array(
		'font-size'=>'30',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'article_font_text'=>array(
		'font-size'=>'',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'post_detail_look'=>'3',
	'h1_font'=>array(
		'font-size'=>'30',
		'color'=>'',
	),
	'h2_font'=>array(
		'font-size'=>'23',
		'color'=>'',
	),
	'h3_font'=>array(
		'font-size'=>'18',
		'color'=>'',
	),
	'h4_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h5_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h6_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'li'=>'1',
	'title_font'=>array(
		'font-family'=>'Crete Round',
		'weight'=>'400',
		'color'=>'',
	),
	'font'=>array(
		'font-size'=>'16',
		'font-family'=>'Open Sans',
		'weight'=>'400',
		'line-height'=>'',
		'color'=>'#111111',
	),
	'link_color'=>'#0cbda0',
),

'blog_footer' => array(
	'show'=>'global'
),
'blog_header' => array(
	'show'=>'global',
)
);
