<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'44',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'video',
						'content'=>'',
						'style'=>array(
							'response'=>'1',
							'vwidth'=>'',
							'height'=>'',
							'code'=>'',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('Text tlačítka','cms_ve'),
						'style'=>array(
							'link'=>array(
								'link'=>'',
							),
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'39',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#d92045',
									'color2'=>'',
								),
								'corner'=>'5',
								'border-color'=>'',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Definice problému <br />a nabídka řešení','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'32',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a tincidunt lacus, ac cursus velit. Morbi viverra suscipit purus non imperdiet. Nam id lorem sit amet elit accumsan iaculis. Nulla eleifend elementum enim, eget tempus lacus tincidunt in. Vestibulum est ligula, sollicitudin non consectetur ac, eleifend in ligula. Praesent tincidunt lacus cursus, vehicula eros eu, laoreet nisl. In placerat vestibulum enim id imperdiet. In condimentum diam tortor, at ornare diam varius vel. Sed vel leo est. Vivamus id nisi et purus mollis venenatis in ac orci. Donec tristique ut nunc vel porttitor.</p><p>Mauris quis nisl vel arcu posuere tincidunt vitae sit amet ipsum. Etiam arcu dui, laoreet vel justo ut, pulvinar porta augue. Nunc auctor nisi eget pharetra molestie. Nulla dignissim felis vel libero porttitor, ut fermentum felis dictum. Morbi id nisl nec nibh cursus semper. Nullam et pretium nunc, sed hendrerit magna. Phasellus semper risus et adipiscing tempor. Curabitur in tellus nec elit interdum pulvinar. Fusce id velit urna. Praesent rhoncus ultrices arcu sed cursus. Aliquam erat volutpat.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'',
							),
							'li'=>'1',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'normal',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#1786bd',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Co získáte?','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a tincidunt lacus, ac cursus velit. Morbi viverra suscipit purus non imperdiet. Nam id lorem sit amet elit accumsan iaculis.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'',
							),
							'li'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'bullets',
						'content'=>'',
						'style'=>array(
							'bullets'=>array(
								'0'=>array(
									'title'=>'Lorem ipsum',
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
								),
								'1'=>array(
									'title'=>'Lorem ipsum',
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
								),
								'2'=>array(
									'title'=>'Lorem ipsum',
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
								),
								'3'=>array(
									'title'=>'Lorem ipsum',
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
								),
							),
							'type'=>'image',
							'style_decimal'=>'1',
							'start_number'=>'1',
							'style_image'=>'2',
							'icon'=>'2',
							'bullet_color'=>'#0e588a',
							'custom_image'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'normal',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Reference','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'32',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
									'name'=>__('Jan Novák','cms_ve'),
									'company'=>__('Grafik','cms_ve'),
									'image'=>'',
								),
								'1'=>array(
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
									'name'=>__('Jan Novák','cms_ve'),
									'company'=>__('Grafik','cms_ve'),
									'image'=>'',
								),
								'2'=>array(
									'text'=>'Maecenas at fringilla enim. Proin ullamcorper orci at ipsum lacinia, vitae sagittis eros suscipit. Mauris tellus dui, sagittis ac orci fermentum, tempor scelerisque mauris',
									'name'=>__('Jan Novák','cms_ve'),
									'company'=>__('Grafik','cms_ve'),
									'image'=>'',
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
							),
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Reference','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'32',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a tincidunt lacus, ac cursus velit. Morbi viverra suscipit purus non imperdiet. Nam id lorem sit amet elit accumsan iaculis. Nulla eleifend elementum enim, eget tempus lacus tincidunt in. Vestibulum est ligula, sollicitudin non consectetur ac, eleifend in ligula. Praesent tincidunt lacus cursus, vehicula eros eu, laoreet nisl. In placerat vestibulum enim id imperdiet. In condimentum diam tortor, at ornare diam varius vel. Sed vel leo est. Vivamus id nisi et purus mollis venenatis in ac orci. Donec tristique ut nunc vel porttitor.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'',
							),
							'li'=>'1',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'32',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a tincidunt lacus, ac cursus velit. Morbi viverra suscipit purus non imperdiet. Nam id lorem sit amet elit accumsan iaculis. Nulla eleifend elementum enim, eget tempus lacus tincidunt in. Vestibulum est ligula, sollicitudin non consectetur ac, eleifend in ligula. Praesent tincidunt lacus cursus, vehicula eros eu, laoreet nisl. In placerat vestibulum enim id imperdiet. In condimentum diam tortor, at ornare diam varius vel. Sed vel leo est. Vivamus id nisi et purus mollis venenatis in ac orci. Donec tristique ut nunc vel porttitor.</p><p>Mauris quis nisl vel arcu posuere tincidunt vitae sit amet ipsum. Etiam arcu dui, laoreet vel justo ut, pulvinar porta augue. Nunc auctor nisi eget pharetra molestie. Nulla dignissim felis vel libero porttitor, ut fermentum felis dictum. Morbi id nisl nec nibh cursus semper. Nullam et pretium nunc, sed hendrerit magna. Phasellus semper risus et adipiscing tempor. Curabitur in tellus nec elit interdum pulvinar. Fusce id velit urna. Praesent rhoncus ultrices arcu sed cursus. Aliquam erat volutpat.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'',
							),
							'li'=>'1',
						),
					),
					'4'=>array(
						'type'=>'countdown',
						'content'=>array(
							'date'=>'30.05.2014',
							'hour'=>'0',
							'minute'=>'0',
						),
						'style'=>array(
							'style'=>'1',
							'font'=>array(
								'font-size'=>'46',
								'font-family'=>'',
								'weight'=>'',
							),
							'background-color'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'40',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'5'=>array(
						'type'=>'button',
						'content'=>__('Text tlačítka','cms_ve'),
						'style'=>array(
							'link'=>array(
								'link'=>'',
							),
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'39',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#d92045',
									'color2'=>'',
								),
								'corner'=>'5',
								'border-color'=>'',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_color'=>'#ebebeb') 
);
$config['config']=array(
  'styles'=>true,
  'body_class'=>'fixed_template'
);