<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'cover'=>'cover',
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'bg/smiling-girl.jpg',
				'imageid'=>'30',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'full_height'=>'1',
				'noheader'=>'1',
				'centered_content'=>'1',
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'row_anchor'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1>'.__('Můj příběh','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'60',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.1',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>'.__('Tady bude vaše Jedinečná expertní věta.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'row_anchor'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2>'.__('První podnadpis','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>'.__('Tady bude text vašeho Expertního autentického příběhu. Dodržujet základní typografická pravidla - dobrá velikost písma , krátké odstavce, používání podnadpisů, <strong>zvýrazňování</strong> textu nebo odrážky.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'50',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<h2>'.__('Druhý podnadpis','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum, nisl at ultrices bibendum, est enim mattis nunc, in imperdiet massa enim at lectus. Vestibulum facilisis leo non mi lacinia scelerisque quis eu lorem. Pellentesque sit amet semper quam, ac vehicula orci. Integer vel nulla pellentesque, ultricies mauris at, lobortis lorem. Quisque magna arcu, tristique vel orci eu, egestas posuere turpis. Pellentesque ornare consectetur turpis ac tempus. Mauris sagittis justo ut metus blandit dapibus. Sed eget nisi et felis pharetra semper.</p>
<p>Donec id tempor ipsum, ut sodales ex. Sed libero tellus, hendrerit eget massa vel, convallis porttitor diam. Sed ex quam, mattis eu felis quis, mattis gravida magna. Proin accumsan tincidunt venenatis. Maecenas sit amet sapien sed mauris viverra mattis. Proin vel nunc sit amet libero consectetur viverra vitae ac tortor. Curabitur sed augue egestas, finibus lectus eu, suscipit eros. Cras et purus dapibus, condimentum purus vel, tempor dui. Nulla facilisi. Sed efficitur turpis eget eleifend vulputate. Suspendisse placerat nulla ut vehicula tempus. Vestibulum in sodales turpis. Duis a imperdiet nisl. In quis mi maximus, accumsan magna fermentum, vestibulum odio. Ut accumsan mollis cursus.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'17',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'webs/blog_pzp/girl1.jpeg',
								'imageid'=>'',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
					'1'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'webs/blog_pzp/girl2.jpeg',
								'imageid'=>'',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
					'2'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'webs/blog_pzp/girl3.jpeg',
								'imageid'=>'',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
				),
			),
		),
	),
);

$page=array(
  'page'=>array(      
      'title' => __('Můj příběh','cms_ve'),   
      'slug' => __('muj-pribeh','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array(),
  'layer'=>base64_encode(serialize($temp_layer)),
);
