<?php
$web_setting=array(
	've_header' => array(
		'logo_setting'=>'text',
		'logo'=>'',
		'logo_text'=>__('Osobni blog','cms_ve'),
		'logo_font'=>array(
			'font-size'=>'22',
			'font-family'=>'Open Sans',
			'weight'=>'600',
			'color'=>'#000000',
		),
		'menu'=>$installed_menus['main'],
		'background_color'=>array(
			'color1'=>'#ffffff',
			'color2'=>'',
			'transparency'=>'100',
		),
		'appearance'=>'type1',
		'menu_font'=>array(
			'font-size'=>'15',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#3b3b3b',
		),
		'menu_active_color'=>'#c42040',
		'menu_submenu_text_color'=>'#ffffff',
		'menu_bg'=>array(
			'color1'=>'#121212',
			'color2'=>'',
		),
		'before_header'=>'',
		'background_image'=>array(
			'overlay_color'=>'#158ebf',
			'overlay_transparency'=>'80',
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
		),
		'header_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
		'header_padding'=>'15',
		'background_color_fix'=>array(
			'color1'=>'',
			'color2'=>'',
			'transparency'=>'100',
		),
		'header_padding_fix'=>array(
			'size'=>'',
		),
	),
        
	've_footer' => array(
		'custom_footer'=>'',
		'appearance'=>'type2',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'#1f1f1f',
			'color2'=>'',
			'transparency'=>'100',
		),
		'background_image'=>array(
			'overlay_color'=>'#158ebf',
			'overlay_transparency'=>'80',
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#7a7a7a',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),
  
	've_appearance' => array(
		'background_color'=>'#ffffff',
		'background_image'=>array(
			'cover'=>'cover',
			'color_filter'=>'color_filter',
			'overlay_color'=>'#000000',
			'overlay_transparency'=>'10',
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
			'pattern'=>'',
		),
		'title_font'=>array(
			'font-family'=>'Open Sans',
			'weight'=>'600',
			'color'=>'',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'Open Sans',
			'weight'=>'400',
			'line-height'=>'',
			'color'=>'',
		),
		'link_color'=>'#c42040',
		'h1_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h2_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h3_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h4_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h5_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h6_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'li'=>'',
	),
  
'blog_sidebars' => array(
          	'sidebar_blog'=>$installed_sidebars['main'],
          	'sidebar_category'=>$installed_sidebars['main'],
          	'sidebar_post'=>$installed_sidebars['main'],
          	'sidebar_author'=>$installed_sidebars['main'],
          	'sidebar_tag'=>$installed_sidebars['main'],
          	'sidebar_search'=>$installed_sidebars['main'],
),    
'blog_appearance' => array(
	'appearance'=>'style4',
	'background_color'=>'#ffffff',
	'background_image'=>array(
		'overlay_color'=>'#158ebf',
		'overlay_transparency'=>'80',
		'position'=>'center center',
		'repeat'=>'no-repeat',
		'image'=>'',
		'imageid'=>'',
		'pattern'=>'',
	),
	'blog_sidebar'=>'1',
	'structure'=>'right',
	'sidebar_font'=>array(
		'font-size'=>'17',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'tb_background'=>array(
		'color1'=>'#1f1f1f',
		'color2'=>'',
	),
	'tb_font'=>array(
		'font-size'=>'30',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'#ffffff',
	),
	'post_look'=>'1',
	'excerpt_length'=>array(
		'size'=>'',
	),
	'show_button'=>'1',
	'button_color'=>'#c42040',
	'article_font'=>array(
		'font-size'=>'35',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'article_font_text'=>array(
		'font-size'=>'',
		'font-family'=>'',
		'weight'=>'',
		'line-height'=>'',
		'color'=>'',
	),
	'post_detail_look'=>'2',
	'h1_font'=>array(
		'font-size'=>'30',
		'color'=>'',
	),
	'h2_font'=>array(
		'font-size'=>'23',
		'color'=>'',
	),
	'h3_font'=>array(
		'font-size'=>'18',
		'color'=>'',
	),
	'h4_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h5_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'h6_font'=>array(
		'font-size'=>'14',
		'color'=>'',
	),
	'li'=>'1',
	'custom_blog_fonts'=>'1',
	'title_font'=>array(
		'font-family'=>'Open Sans',
		'weight'=>'700',
		'color'=>'',
	),
	'font'=>array(
		'font-size'=>'16',
		'font-family'=>'Open Sans',
		'weight'=>'400',
		'line-height'=>'',
		'color'=>'#111111',
	),
	'link_color'=>'#c42040',
),

'blog_footer' => array(
	'show'=>'global'
),
'blog_header' => array(
	'show'=>'global',
)
);
