<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#daedf5',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#0c79a8',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#00628f',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'70',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Jan Novák vás zve na webinář','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, ectetur adipiscing elit. Donec ornare nibh non.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'42',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#f0f0f0',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'26',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
              'popup_text'=>__('Registrovat se na webinář','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'35',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'5',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'18',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#003d5c',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'calendar',
										'size'=>'71',
										'color'=>'#a8daf0',
									),
									'title'=>__('28. května','cms_ve'),
									'text'=>__('ve 21.00','cms_ve'),
								),
							),
							'cols'=>'one',
							'style'=>'3',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'300',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">'.__('Webinář doprovází a otázky klade Jan Novák.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">'.__('Našimi hosty jsou:','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Co vám přinese tento živý webinář?','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit. Duis ut ante vestibulum, varius neque nec, mollis eros. Integer scelerisque ante et vestibulum tincidunt.</li>
<li>Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. Pellentesque suscipit aliquam tincidunt.</li>
<li>Aliquam a mauris sodales, interdum felis nec, blandit metus. Quisque tortor augue, imperdiet nec fringilla ac, mollis aliquam magna. Vivamus ut sem ut dolor dictum posuere. Curabitur quis convallis arcu.</li>
<li>Nam hendrerit turpis est, ut iaculis nulla viverra eu. Aenean eu sollicitudin lacus, in pretium est.</li>
</ul>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'42',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;"><strong>'.__('POZOR: Místa pro vysílání mohou být omezena, proto si je raději rezervujte a přijďte včas, prosím. Obvykle je webinář vždy plně obsazen.','cms_ve').'</strong></p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ff0000',
							),
							'li'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Chytněte své místo raději ihned a rozhodně přijďte včas!','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#f0f0f0',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'26',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Registrovat se na webinář','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'40',
									'font-family'=>'Open Sans',
									'weight'=>'600',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'5',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'10',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'align'=>'center',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_color'=>'#e8e8e8') 
);
$config['config']=array(
  'styles'=>true,
);