<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#158ebf',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'#ffffff',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'60',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'full_height'=>'full_height',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">DĚKUJEME ZA VAŠE HODNOCENÍ</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'750',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'box',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">Napište text s poděkováním. Také na tuto stránku můžete dát nějaký dáreček, např. nějaký materiál ke stažení.</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'',
											'font-family'=>'',
											'weight'=>'',
											'line-height'=>'',
											'color'=>'',
										),
										'li'=>'',
										'style'=>'1',
										'p-background-color'=>array(
											'color1'=>'#e8e8e8',
											'color2'=>'',
											'transparency'=>'100',
										),
									),
									'config'=>array(
										'max_width'=>'',
										'margin_top'=>'0',
										'margin_bottom'=>'40',
										'delay'=>'',
										'animate'=>'',
										'id'=>'',
										'class'=>'',
									),
								),
								'1'=>array(
									'type'=>'button',
									'content'=>'ZPĚT NA ÚVODNÍ STRÁNKU',
									'style'=>array(
										'show'=>'url',
										'link'=>array(
											'page'=>'8',
											'link'=>'',
										),
										'popup'=>'',
										'align'=>'center',
										'button'=>array(
											'style'=>'9',
											'font'=>array(
												'font-size'=>'19',
												'font-family'=>'',
												'weight'=>'',
												'color'=>'#1a1a1a',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffcc00',
												'color2'=>'',
											),
											'corner'=>'0',
											'height_padding'=>'0.8',
											'width_padding'=>'1.6',
											'border-color'=>'',
											'hover_color'=>array(
												'color1'=>'',
												'color2'=>'',
											),
											'hover_effect'=>'scale',
											'hover_font_color'=>'',
											'border_hover-color'=>'',
										),
										'text2'=>'Text tlačítka',
										'show2'=>'url',
										'link2'=>array(
											'page'=>'',
											'link'=>'',
										),
										'popup2'=>'',
										'button2'=>array(
											'style'=>'1',
											'font'=>array(
												'font-size'=>'30',
												'font-family'=>'',
												'weight'=>'',
												'color'=>'#2b2b2b',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffde21',
												'color2'=>'#ffcc00',
											),
											'corner'=>'0',
											'height_padding'=>'0.5',
											'width_padding'=>'1.2',
											'border-color'=>'',
											'hover_color'=>array(
												'color1'=>'',
												'color2'=>'',
											),
											'hover_effect'=>'',
											'hover_font_color'=>'',
											'border_hover-color'=>'',
										),
									),
								),
							),
						),
						'style'=>array(
							'background_color'=>array(
								'color1'=>'#ffffff',
								'color2'=>'',
								'transparency'=>'100',
							),
							'background_image'=>array(
								'position'=>'center center',
								'repeat'=>'no-repeat',
								'image'=>'',
								'imageid'=>'',
								'pattern'=>'',
							),
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#111111',
							),
							'link-color'=>'#158ebf',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'corner'=>'0',
							'padding'=>array(
								'top'=>'60',
								'bottom'=>'50',
								'left'=>'40',
								'right'=>'40',
							),
							'box-shadow'=>array(
								'horizontal'=>'0',
								'vertical'=>'0',
								'size'=>'0',
								'transparency'=>'10',
							),
							'title'=>'',
							'title-font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'title_bg'=>array(
								'color1'=>'#eeeeee',
								'color2'=>'',
								'transparency'=>'100',
							),
							'title_border'=>array(
								'size'=>'1',
								'color'=>'#dddddd',
							),
						),
						'config'=>array(
							'max_width'=>'650',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);

$setting=array ( 
	've_header' => array(
		'show'=>'noheader',
	),

	've_footer' => array(
		'show'=>'page',
		'custom_footer'=>'39',
		'hide_footer_end'=>'1',
		'appearance'=>'type2',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'#171616',
			'color2'=>'',
			'transparency'=>'100',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
		),
		'font'=>array(
			'font-size'=>'',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#7a7a7a',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),
);

$page=array(
  'page'=>array(      
      'title' => __('Děkujeme','cms_ve'),   
      'slug' => __('dekujeme','cms_ve'), 
      'parent' => 'questions', 
      'theme' => 'page/1/',
  ),
  'setting'=>$setting,
  'layer'=>base64_encode(serialize($temp_layer)),
);
