<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#158ebf',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'#ffffff',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#00628f',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">Název vysílaného webináře</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'50',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'video',
						'content'=>'',
						'style'=>array(
							'code'=>'',
							'align'=>'center',
						),
					),
					'1'=>array(
						'type'=>'like',
						'content'=>array(
							'page'=>'110',
							'link'=>'',
						),
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'setting'=>array(
								'share'=>'share',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>'Jan Novák',
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_position'=>array(
								'font-size'=>'12',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#888888',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare nibh non tellus varius egestas. Nunc quis purus justo. Etiam sodales sagittis dui eu luctus. Nullam id leo nec orci varius porttitor vehicula in ante. Duis ut ante vestibulum, varius neque nec, mollis eros.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Máte dotaz?</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'html',
						'content'=>'<p><br><br>Zde vložte javascript kód pluginu pro vypsání komentářů, které chcete na stránce použít. Pro účely vysílání webináře je potřeba, aby bylo možné napsat komentář bez nutnosti znovunačtení stránky. Vhodné jsou například komentáře <a href="https://disqus.com" target="_blank">disqus</a>.<br><br></p>',
						'style'=>array(
						),
					),
					'2'=>array(
						'type'=>'twocols',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'fcomments',
									'content'=>array(
										'page'=>'110',
										'link'=>'',
									),
									'style'=>array(
										'width'=>'100%',
										'per_page'=>'50',
										'scheme'=>'light',
									),
								),
							),
							'1'=>array(
								'0'=>array(
									'type'=>'wpcomments',
									'content'=>'',
									'style'=>array(
										'style'=>'1',
										'button'=>array(
											'style'=>'9',
											'font'=>array(
												'font-size'=>'19',
												'font-family'=>'',
												'weight'=>'',
												'color'=>'#ffffff',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#158ebf',
												'color2'=>'',
											),
											'corner'=>'0',
											'height_padding'=>'0.8',
											'width_padding'=>'1.6',
											'border-color'=>'',
											'hover_color'=>array(
												'color1'=>'',
												'color2'=>'',
											),
											'hover_effect'=>'scale',
											'hover_font_color'=>'',
											'border_hover-color'=>'',
										),
									),
								),
							),
						),
						'style'=>array(
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor set</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
				),
			),
		),
	),
);

$setting=array ( 
	've_header' => array(
		'show'=>'noheader',
	),

	've_footer' => array(
		'show'=>'page',
		'custom_footer'=>'39',
		'hide_footer_end'=>'1',
		'appearance'=>'type1',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'',
			'color2'=>'',
			'transparency'=>'100',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#7a7a7a',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),
 
	've_appearance' => array(
		'background_color'=>'#e8e8e8',
	),

);

$page=array(
  'page'=>array(      
      'title' => __('Přednáška','cms_ve'),   
      'slug' => __('prednaska','cms_ve'), 
      'theme' => 'webinar/2/',
  ),
  'setting'=>$setting,
  'layer'=>base64_encode(serialize($temp_layer)),
);
