<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#158ebf',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'#ffffff',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'70',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#00628f',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Jan Novák vás zve na webinář</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, ectetur adipiscing elit. Donec ornare nibh non.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'42',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>array(
							'api'=>'se',
						),
						'style'=>array(
							'type'=>'smartemailing',
							'html'=>'',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>array(
								'page'=>'',
								'link'=>'',
							),
							'url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#f0f0f0',
							'button_text'=>'',
							'button'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'19',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#158ebf',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.6',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'scale',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'popup'=>'1',
							'popup_title'=>'Zadejte svůj e-mail a zajistěte si místo na webináři.',
							'popup_type'=>'button',
							'image'=>'',
							'popup_text'=>'Registrovat se na webinář',
							'popupbutton'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#1a1a1a',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.6',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'scale',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'link_text'=>'Registrovat se',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'18',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#003d5c',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'calendar',
										'size'=>'71',
										'color'=>'#cce5f0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>'28. května',
									'text'=>'ve 21.00',
									'button_text'=>'Více informací →',
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'3',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'2',
								'font'=>array(
									'font-size'=>'13',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#737373',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'90',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'300',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">Webinář doprovází a otázky klade Jan Novák.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>'Jan Novák',
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">Našimi hosty jsou:</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>'Jan Novák',
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>'Jan Novák',
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>'Jan Novák',
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'Co vám přinese tento živý webinář?',
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit. Duis ut ante vestibulum, varius neque nec, mollis eros. Integer scelerisque ante et vestibulum tincidunt.</li>
<li>Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. Pellentesque suscipit aliquam tincidunt.</li>
<li>Aliquam a mauris sodales, interdum felis nec, blandit metus. Quisque tortor augue, imperdiet nec fringilla ac, mollis aliquam magna. Vivamus ut sem ut dolor dictum posuere. Curabitur quis convallis arcu.</li>
<li>Nam hendrerit turpis est, ut iaculis nulla viverra eu. Aenean eu sollicitudin lacus, in pretium est.</li>
</ul>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'42',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;"><strong>POZOR: Místa pro vysílání mohou být omezena, proto si je raději rezervujte a přijďte včas, prosím. Obvykle je webinář vždy plně obsazen.</strong></p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ff0000',
							),
							'li'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Chytněte své místo raději ihned a rozhodně přijďte včas!</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>array(
							'api'=>'se',
						),
						'style'=>array(
							'type'=>'smartemailing',
							'html'=>'',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>array(
								'page'=>'',
								'link'=>'',
							),
							'url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'18',
								'color'=>'',
							),
							'background'=>'#f0f0f0',
							'button_text'=>'',
							'button'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'19',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#158ebf',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.6',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'scale',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'popup'=>'1',
							'popup_title'=>'Zadejte svůj e-mail a zajistěte si místo na webináři.',
							'popup_type'=>'button',
							'image'=>'',
							'popup_text'=>'Registrovat se na webinář',
							'popupbutton'=>array(
								'style'=>'9',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#158ebf',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.6',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'scale',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'link_text'=>'Registrovat se',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'10',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'align'=>'center',
						),
					),
				),
			),
		),
	),
);

$setting=array ( 
	've_header' => array(
		'show'=>'noheader',
	),

	've_footer' => array(
		'show'=>'page',
		'custom_footer'=>'39',
		'hide_footer_end'=>'1',
		'appearance'=>'type1',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'',
			'color2'=>'',
			'transparency'=>'100',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
		),
		'font'=>array(
			'font-size'=>'15',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#7a7a7a',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),
 
	've_appearance' => array(
		'page_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
		'background_color'=>'#e8e8e8',
		'background_setting'=>'image',
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
			'imageid'=>'',
			'pattern'=>'',
		),
		'background_video_mp4'=>'',
		'background_video_webm'=>'',
		'background_video_ogg'=>'',
		'font'=>array(
			'font-size'=>'',
			'font-family'=>'',
			'weight'=>'',
			'line-height'=>'',
			'color'=>'',
		),
		'link_color'=>'',
		'title_font'=>array(
			'font-family'=>'',
			'weight'=>'',
			'color'=>'',
		),
		'h1_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h2_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h3_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h4_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h5_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'h6_font'=>array(
			'font-size'=>'',
			'color'=>'',
		),
		'li'=>'',
	),

);

$page=array(
  'page'=>array(      
      'title' => __('Vysílání','cms_ve'),   
      'slug' => __('vysilani','cms_ve'), 
      'parent' => 'webinar_landing',
      'theme' => 'webinar/live2/',
  ),
  'setting'=>$setting,
  'layer'=>base64_encode(serialize($temp_layer)),
);
