<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#209ccf',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c8dce6',
			),
			'link_color'=>'#ffffff',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'full_height'=>'full_height',
				'noheader'=>'noheader',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Děkujeme','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'90',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Děkujeme, že jste se registrovali. Jako dárek pro vás máme připravený e-book zdarma ke stažení.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'setting'=>array(
								'share'=>'share',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'button',
						'content'=>__('Stáhnout e-book!','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'6',
								'font'=>array(
									'font-size'=>'35',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#141414',
									'text-shadow'=>'light',
								),
								'background_color'=>array(
									'color1'=>'#ffcc00',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.7',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'scale',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'text2'=>__('Text tlačítka','cms_ve'),
							'show2'=>'url',
							'link2'=>array(
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'8',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'4'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Je něco v nepořádku?','cms_ve').' <a href="http://">'.__('Kontaktujte nás','cms_ve').'</a>.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'13',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);

$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();

$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('font'=>array(
			'font-size'=>'18',
			'font-family'=>'',
			'weight'=>'',
			'line-height'=>'',
			'color'=>'',
		),) 
);
