<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'14',
			),
			'border-top'=>array(
				'size'=>'1',
				'style'=>'solid',
				'color'=>'#f0f0f0',
			),
			'border-bottom'=>array(
				'size'=>'1',
				'style'=>'solid',
				'color'=>'#f0f0f0',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'video',
						'content'=>'',
						'style'=>array(
							'max-width'=>'',
							'code'=>'',
							'align'=>'center',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1>'.__('Nejdůležitější nadpis stránky pro přilákání pozornosti návštěvníka','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'16',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#ededed',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#219ed1',
									'color2'=>'#158ebf',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Mám zájem','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a registrujte se.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'25',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#219ed1',
									'color2'=>'#158ebf',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'align'=>'left',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'rocket',
										'size'=>'50',
										'color'=>'#158ebf',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. ',
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'lightbulb-1',
										'size'=>'50',
										'color'=>'#158ebf',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. ',
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'gift',
										'size'=>'50',
										'color'=>'#158ebf',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. ',
								),
							),
							'cols'=>'three',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
					),
					'1'=>array(
						'type'=>'graphic',
						'content'=>'',
						'style'=>array(
							'style'=>array(
								'item'=>'9',
								'itemtype'=>'hr',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'80',
							'margin_bottom'=>'70',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'image_text',
						'content'=>'<div class="element_content">
<div class="in_element_content entry_content element_text_size_small element_text_li">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoreet porttitor ut nec velit. Duis ut ante vestibulum, varius neque nec, mollis eros. Integer scelerisque ante et vestibulum tincidunt. Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. Pellentesque suscipit aliquam tincidunt. Proin luctus erat in rutrum bibendum. Aliquam quis libero eu urna hendrerit elementum in sed dolor. Pellentesque suscipit aliquam tincidunt.</p>
</div>
</div>',
						'style'=>array(
							'title'=>__('Něco o projektu','cms_ve'),
							'image'=>get_template_url_image().'/modules/visualeditor/templates/images/image.png',
							'style'=>'1',
							'align'=>'right',
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#f5f5f5',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'1',
				'style'=>'solid',
				'color'=>'#ededed',
			),
			'border-bottom'=>array(
				'size'=>'1',
				'style'=>'solid',
				'color'=>'#ededed',
			),
			'padding_top'=>'70',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
                  'name'=>__('Honza','cms_ve'),
									'company'=>__('Informatik','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
								),
							),
							'cols'=>'one',
							'style'=>'5',
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Nejnovější články','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'26',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'recent_posts',
						'content'=>'',
						'style'=>array(
							'cols'=>'three',
							'number'=>'3',
							'style'=>'1',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#2e2e2e',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'50',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Nadpis, klidně na dva tři řádky, který přiměje <br />návštěvníka, aby vám dal svůj kontakt.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'Open Sans',
								'weight'=>'400',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'3',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#ededed',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#219ed1',
									'color2'=>'#158ebf',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Mám zájem','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a registrujte se.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'28',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#219ed1',
									'color2'=>'#158ebf',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'align'=>'center',
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array ();
$config['config']=array();
