<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#cccccc',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#141414',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Jan Novák vás zve na webinář','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'5',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, ectetur adipiscing elit. Donec ornare nibh non tellus.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Registrovat se na webinář','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'40',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
						),
					),
					'3'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c3ebe2',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#0c9978',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'calendar',
										'size'=>'52',
										'color'=>'#ffffff',
									),
									'title'=>__('28. května','cms_ve'),
									'text'=>__('ve 21.00','cms_ve'),
								),
							),
							'cols'=>'one',
							'style'=>'3',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
							),
						),
						'config'=>array(
							'max_width'=>'250',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Co vám přinese tento živý webinář?','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare nibh non tellus varius egestas. Nunc quis purus justo. Etiam sodales sagittis dui eu luctus. Nullam id leo nec orci varius porttitor vehicula in ante. Ut eu nulla eget augue laoreet ultrices. Praesent quis sapien enim. Curabitur arcu risus, pharetra nec elit at, fermentum luctus nisi. Proin sit amet vestibulum ligula. Nullam leo augue, tincidunt in arcu ac, auctor faucibus dolor. Nunc et nisi lectus.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('A jaká jsou hlavní témata?','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'bullets',
						'content'=>'',
						'style'=>array(
							'bullets'=>array(
								'0'=>array(
									'title'=>'Etiam euismod purus',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
								),
								'1'=>array(
									'title'=>'Etiam euismod purus',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
								),
								'2'=>array(
									'title'=>'Etiam euismod purus',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
								),
								'3'=>array(
									'title'=>'Etiam euismod purus',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
								),
							),
							'type'=>'image',
							'style_decimal'=>'1',
							'start_number'=>'1',
							'style_image'=>'2',
							'icon'=>'2',
							'bullet_color'=>'#0c9978',
							'custom_image'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c3ebe2',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#0c9978',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Webinář doprovází a otázky klade Jan Novák.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Našimi hosty jsou:','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
								'3'=>array(
									'title'=>__('Jan Novák','cms_ve'),
									'position'=>'',
									'text'=>'',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'four',
							'style'=>'1',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#d6d6d6',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#141414',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'form-style'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_text'=>__('Registrovat se na webinář','cms_ve'),
							'popup_title'=>__('Zadejte svůj e-mail a zajistěte si místo na webináři.','cms_ve'),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'40',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
						),
					),
					'2'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'align'=>'center',
						),
					),
				),
			),
		),
	),
);

$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_color' => '#141414') 
);
$config['layer']=$temp_layer=base64_encode(serialize($temp_layer));
$config['config']=array(
  'body_class'=>'fixed_narrow_width_page'
);