<?php
$color_set=array(
    'background'=>'#41a0a9',
    'background_image'=>MW_IMAGE_LIBRARY.'webs/web1/bg_blue.jpg',
    'bg_text'=>'#cedee0',
    'bg_title'=>'#ffffff',
    'button_bg'=>'#e4960e',
    'button_hover_bg'=>'#e6810e',
    'button_text'=>'#ffffff',
);
