<?php
$color_set=array(
    'background'=>'#1f547e',
    'background_image'=>MW_IMAGE_LIBRARY.'webs/web1/bg_blue2.jpg',
    'bg_text'=>'#c4d7e6',
    'bg_title'=>'#ffffff',
    'button_bg'=>'#e4960e',
    'button_hover_bg'=>'#e6810e',
    'button_text'=>'#ffffff',
);
