<?php
$color_set=array(
    'background'=>'#259072',
    'background_image'=>MW_IMAGE_LIBRARY.'webs/web1/bg_green.jpg',
    'bg_text'=>'#caebe2',
    'bg_title'=>'#ffffff',
    'button_bg'=>'#e4960e',
    'button_hover_bg'=>'#e6810e',
    'button_text'=>'#ffffff',
);
