<?php
$color_set=array(
    'background'=>'#c0466f',
    'background_image'=>MW_IMAGE_LIBRARY.'webs/web1/bg_pink.jpg',
    'bg_text'=>'#f1d9e1',
    'bg_title'=>'#ffffff',
    'button_bg'=>'#e4960e',
    'button_hover_bg'=>'#e6810e',
    'button_text'=>'#ffffff',
);
