<?php
$color_set=array(
    'background'=>'#524e73',
    'background_image'=>MW_IMAGE_LIBRARY.'webs/web1/bg_purple.jpg',
    'bg_text'=>'#d1ceeb',
    'bg_title'=>'#ffffff',
    'button_bg'=>'#e4960e',
    'button_hover_bg'=>'#e6810e',
    'button_text'=>'#ffffff',
);
