<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'',
				'overlay_transparency'=>'90',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#aaaaaa',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'120',
			'padding_bottom'=>'120',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
								'imageid'=>'',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'6',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">Lorem ipsum dolor set</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'80',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis scelerisque erat, egestas mollis urna. Nullam purus quam, sagittis sit amet metus sit amet, ultrices malesuada nibh. Integer auctor velit eu mattis tincidunt. In semper tempor augue congue tempor. Nam posuere suscipit pellentesque. Morbi ultrices massa ut lorem lobortis, nec suscipit sem tristique. Aenean vel porta sem.</p>
<p>Pellentesque blandit ligula posuere ligula ultrices pellentesque. Nunc leo mauris, placerat vestibulum tellus et, ullamcorper sodales arcu. Mauris eget felis nisi. Nam feugiat, tellus at varius aliquam, justo turpis aliquet nulla, quis molestie orci neque sed nulla. Maecenas eget dignissim justo, vel aliquam elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi porttitor tortor non mi maximus aliquet. Phasellus nec neque et enim commodo iaculis imperdiet eu turpis. Nunc sed risus ante. Nulla condimentum nisl vel sapien ultricies finibus. Curabitur eget lectus condimentum, congue urna sit amet, accumsan augue. Duis vulputate diam at metus finibus, ac pulvinar ante lacinia. Sed mattis hendrerit magna, quis molestie felis. Phasellus eget tincidunt enim, id accumsan nisi. Proin viverra, orci vel tristique semper, orci diam lobortis ligula, at scelerisque magna nisl sed ex.</p>
<p>Aenean dictum tellus ac interdum placerat. Sed laoreet felis vitae lorem consequat, sit amet ultrices odio aliquam. Curabitur rutrum sollicitudin gravida. In massa dui, posuere sed mauris a, convallis dignissim dui. Pellentesque luctus justo sem, ac faucibus tortor dictum aliquam. Curabitur in mauris sed orci ultricies ultricies. Aliquam fringilla lectus eget hendrerit gravida. Pellentesque sit amet tristique augue.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Můj příběh','cms_ve'),   
      'slug' => __('muj-pribeh','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
