<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#007ab3',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'30',
			'padding_bottom'=>'50',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Ceník','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'#c4d8e6',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'pricelist',
						'content'=>'',
						'style'=>array(
							'pricelist'=>array(
								'0'=>array(
									'title'=>__('ZÁKLADNÍ','cms_ve'),
									'price'=>__('490 Kč','cms_ve'),
									'sale_price'=>'',
									'per'=>__('Ročně','cms_ve'),
									'features'=>array(
										'0'=>array(
											'text'=>'Lorem ipsum dolor sit amet',
										),
										'1'=>array(
											'text'=>'Pellentesque sollicitudin',
										),
										'2'=>array(
											'text'=>'Suspendisse dapibus',
										),
										'3'=>array(
											'text'=>'Pellentesque habitant morbi tristiqu',
										),
										'4'=>array(
											'text'=>'Suspendisse dapibus',
										),
										'5'=>array(
											'text'=>'',
										),
									),
									'button_text'=>__('Objednat','cms_ve'),
									'link'=>array(
										'link'=>'http://',
									),
									'text'=>__('Zde můžete zadat nějaký popisek pro tento sloupec ceníku.','cms_ve'),
								),
								'1'=>array(
									'title'=>__('PROFESIONÁLNÍ','cms_ve'),
									'price'=>__('2990 Kč','cms_ve'),
									'sale_price'=>'',
									'per'=>__('Ročně','cms_ve'),
									'features'=>array(
										'0'=>array(
											'text'=>'Lorem ipsum dolor sit amet',
										),
										'1'=>array(
											'text'=>'Pellentesque sollicitudin',
										),
										'2'=>array(
											'text'=>'Suspendisse dapibus',
										),
										'3'=>array(
											'text'=>'Pellentesque habitant morbi tristiqu',
										),
										'4'=>array(
											'text'=>'Suspendisse dapibus',
										),
										'5'=>array(
											'text'=>'Pellentesque sollicitudin',
										),
									),
									'button_text'=>__('Objednat','cms_ve'),
									'link'=>array(
										'link'=>'http://',
									),
									'text'=>__('Zde můžete zadat nějaký popisek pro tento sloupec ceníku.','cms_ve'),
									'popular'=>'1',
								),
								'2'=>array(
									'title'=>__('NEOMEZENÉ','cms_ve'),
									'price'=>__('6990 Kč','cms_ve'),
									'sale_price'=>'',
									'per'=>__('Ročně','cms_ve'),
									'features'=>array(
										'0'=>array(
											'text'=>'Lorem ipsum dolor sit amet',
										),
										'1'=>array(
											'text'=>'Pellentesque sollicitudin',
										),
										'2'=>array(
											'text'=>'Suspendisse dapibus',
										),
										'3'=>array(
											'text'=>'Pellentesque habitant morbi tristiqu',
										),
										'4'=>array(
											'text'=>'Suspendisse dapibus',
										),
										'5'=>array(
											'text'=>'Lorem ipsum dolor sit amet',
										),
									),
									'button_text'=>__('Objednat','cms_ve'),
									'link'=>array(
										'link'=>'http://',
									),
									'text'=>__('Zde můžete zadat nějaký popisek pro tento sloupec ceníku.','cms_ve'),
								),
							),
							'style'=>'1',
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'popular_color'=>'#004c75',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'29',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'50',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'10',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Nejčastěji kladené otázky','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque sollicitudin tortor sit amet ornare posuere. Sed vel varius lectus, ac sagittis lectus. Nullam eros dui, dapibus non purus a, dapibus aliquet orci.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque sollicitudin tortor sit amet ornare posuere. Sed vel varius lectus, ac sagittis lectus. Nullam eros dui, dapibus non purus a, dapibus aliquet orci.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque sollicitudin tortor sit amet ornare posuere. Sed vel varius lectus, ac sagittis lectus. Nullam eros dui, dapibus non purus a, dapibus aliquet orci.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque sollicitudin tortor sit amet ornare posuere. Sed vel varius lectus, ac sagittis lectus. Nullam eros dui, dapibus non purus a, dapibus aliquet orci.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
			'2'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque sollicitudin tortor sit amet ornare posuere. Sed vel varius lectus, ac sagittis lectus. Nullam eros dui, dapibus non purus a, dapibus aliquet orci.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'19',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque sollicitudin tortor sit amet ornare posuere. Sed vel varius lectus, ac sagittis lectus. Nullam eros dui, dapibus non purus a, dapibus aliquet orci.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array();
$config['config']=array();
