<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center bottom',
				'repeat'=>'no-repeat',
				'image'=>$color_set['background_image'],
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'17',
				'font-family'=>'',
				'weight'=>'',
				'color'=>$color_set['bg_text'],
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'0',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>MW_IMAGE_LIBRARY.'book/book.png',
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'left',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1>'.__('Poutavý název ebooku a výzva ke stažení','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'55',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.1',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'5',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'setting'=>array(
								'share'=>'share',
							),
							'align'=>'left',
						),
					),
					'2'=>array(
						'type'=>'text',
						'content'=>'<p>Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla. </p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'button',
						'content'=>__('Stáhnout zdarma','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'left',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'28',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>$color_set['button_bg'],
									'color2'=>'',
								),
								'hover_color'=>array(
									'color1'=>$color_set['button_hover_bg'],
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'#ffffff',
							),
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#000000',
				'color2'=>'',
				'transparency'=>'60',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>$color_set['bg_text'],
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'30',
			'padding_bottom'=>'20',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'numbers',
						'content'=>'',
						'style'=>array(
							'numbers'=>array(
								'0'=>array(
									'type'=>'custom',
									'se'=>'8',
									'number'=>'24',
									'unit'=>'',
									'title'=>__('Stránek','cms_ve'),
								),
								'1'=>array(
									'type'=>'custom',
									'se'=>'8',
									'number'=>'4231',
									'unit'=>'',
									'title'=>__('Čtenářů','cms_ve'),
								),
								'2'=>array(
									'type'=>'custom',
									'se'=>'8',
									'number'=>'2300',
									'unit'=>'',
									'title'=>__('Fanoušků','cms_ve'),
								),
							),
							'style'=>'1',
							'cols'=>'three',
							'number_font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
							),
							'text_font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Co se v ebooku dozvíte','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'80',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'rocket',
										'size'=>'50',
										'color'=>$color_set['background'],
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum.',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'lightbulb-1',
										'size'=>'50',
										'color'=>$color_set['background'],
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum.',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'gift',
										'size'=>'50',
										'color'=>$color_set['background'],
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum.',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>'',
								),
								'3'=>array(
									'icon'=>array(
										'icon'=>'location',
										'size'=>'50',
										'color'=>$color_set['background'],
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum.',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>__('Více informací ›','cms_ve'),
								),
								'4'=>array(
									'icon'=>array(
										'icon'=>'camera',
										'size'=>'50',
										'color'=>$color_set['background'],
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum.',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>__('Více informací ›','cms_ve'),
								),
								'5'=>array(
									'icon'=>array(
										'icon'=>'chat',
										'size'=>'50',
										'color'=>$color_set['background'],
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'Lorem ipsum dolor',
									'text'=>'Curabitur vel mi a odio condimentum dignissim. Mauris iaculis quam id accumsan aliquam. Proin luctus erat in rutrum bibendum.',
									'link'=>array(
										'link'=>'',
									),
									'button_text'=>__('Více informací ›','cms_ve'),
								),
							),
							'cols'=>'three',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'2',
								'font'=>array(
									'font-size'=>'13',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#737373',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'corner'=>'90',
								'border-color'=>'#bdbdbd',
							),
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#cedee0',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'70',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.6',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'580',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'4'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'90',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Co na to čtenáři','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'70',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Vestibulum pellentesque, sem et dignissim dapibus, erat tellus congue lectus, id tempor tortor lectus eget arcu. Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla. ',
									'name'=>__('Honza','cms_ve'),
									'company'=>__('Informatik','cms_ve'),
									'image'=>'/wp-content/themes/mioweb/modules/visualeditor/templates/images/person.jpg',
								),
								'1'=>array(
									'text'=>'Vestibulum pellentesque, sem et dignissim dapibus, erat tellus congue lectus, id tempor tortor lectus eget arcu. Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla. ',
									'name'=>__('Petra','cms_ve'),
									'company'=>__('Finanční poradce','cms_ve'),
									'image'=>'/wp-content/themes/mioweb/modules/visualeditor/templates/images/person.jpg',
								),
								'2'=>array(
									'text'=>'Vestibulum pellentesque, sem et dignissim dapibus, erat tellus congue lectus, id tempor tortor lectus eget arcu. Pellentesque egestas facilisis sem, id placerat tortor. Sed lacinia blandit nisl. Curabitur eu lectus pellentesque, dignissim purus a, porta nulla. ',
									'name'=>__('Honza','cms_ve'),
									'company'=>__('Účetní','cms_ve'),
									'image'=>'/wp-content/themes/mioweb/modules/visualeditor/templates/images/person.jpg',
								),
							),
							'cols'=>'three',
							'style'=>'6',
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'5'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#efefef',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>__('Jméno autora','cms_ve'),
									'position'=>'',
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eget sem vitae neque placerat mattis. Nam nisi ligula, ultricies varius magna quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nisi ligula, ultricies varius magna quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
									'image'=>'',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'4',
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_position'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#888888',
							),
							'font_text'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.6',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Zdarma','cms_ve'),   
      'slug' => __('zdarma','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
