<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center bottom',
				'repeat'=>'no-repeat',
				'image'=>$color_set['background_image'],
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>$color_set['bg_text'],
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'50',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'full_height'=>'full_height',
				'centered_content'=>'centered_content',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Děkujeme :)','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'55',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'box',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">'.__('Dejte poznat, že máte z registrace radost, že jste nadšení, napište text od srdce nebo natočte video, umístěte fotku sebe, týmu aj.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'18',
											'font-family'=>'',
											'weight'=>'',
											'line-height'=>'',
											'color'=>'',
										),
										'li'=>'',
									),
									'config'=>array(
										'max_width'=>'800',
										'margin_top'=>'0',
										'margin_bottom'=>'30',
										'delay'=>'',
										'animate'=>'',
										'id'=>'',
										'class'=>'',
									),
								),
								'1'=>array(
									'type'=>'title',
									'content'=>'<p style="text-align: center;">'.__('Nyní doporučujeme:','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'30',
											'font-family'=>'',
											'weight'=>'',
											'line-height'=>'1.2',
											'color'=>'',
											'text-shadow'=>'none',
										),
										'style'=>'1',
										'border'=>array(
											'size'=>'1',
											'color'=>'#d5d5d5',
										),
										'background-color'=>array(
											'color1'=>'#efefef',
											'color2'=>'',
											'transparency'=>'100',
										),
										'align'=>'center',
									),
								),
								'2'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">'.__('Odkaz na další zajímavý obsah, nebo YouTube kanál, Facebook apod.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'18',
											'font-family'=>'',
											'weight'=>'',
											'line-height'=>'',
											'color'=>'',
										),
										'li'=>'',
									),
									'config'=>array(
										'max_width'=>'800',
										'margin_top'=>'0',
										'margin_bottom'=>'30',
										'delay'=>'',
										'animate'=>'',
										'id'=>'',
										'class'=>'',
									),
								),
								'3'=>array(
									'type'=>'share',
									'content'=>'',
									'style'=>array(
										'show'=>array(
											'facebook'=>'facebook',
											'twitter'=>'twitter',
											'google'=>'google',
										),
										'scheme'=>'1',
									),
								),
							),
						),
						'style'=>array(
							'background_color'=>array(
								'color1'=>'#ffffff',
								'color2'=>'',
								'transparency'=>'100',
							),
							'background_image'=>array(
								'position'=>'center center',
								'repeat'=>'no-repeat',
								'image'=>'',
								'pattern'=>'0',
							),
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#262626',
							),
							'link-color'=>'',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'corner'=>'0',
							'padding'=>array(
								'top'=>'60',
								'bottom'=>'50',
								'left'=>'60',
								'right'=>'60',
							),
							'box-shadow'=>array(
								'horizontal'=>'0',
								'vertical'=>'0',
								'size'=>'0',
								'transparency'=>'10',
							),
							'title'=>'',
							'title-font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'title_bg'=>array(
								'color1'=>'#eeeeee',
								'color2'=>'',
								'transparency'=>'100',
							),
							'title_border'=>array(
								'size'=>'1',
								'color'=>'#dddddd',
							),
						),
						'config'=>array(
							'max_width'=>'550',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Poděkování','cms_ve'),   
      'slug' => __('podekovani','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (
      've_header' => array('show'=>'noheader'),
      've_footer' => array('show'=>'nofooter'),
  ),
  'layer'=>base64_encode(serialize($temp_layer)),
);
