<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'13',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#ededed',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Název vysílaného webináře','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'42',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'setting'=>array(
								'share'=>'share',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'video',
						'content'=>'',
						'style'=>array(
							'max-width'=>'',
							'code'=>'',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'class'=>'',
						),
					),
					'3'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Informace o webináři','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'23',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'4'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare nibh non tellus varius egestas. Nunc quis purus justo. Etiam sodales sagittis dui eu luctus. Nullam id leo nec orci varius porttitor vehicula in ante. Duis ut ante vestibulum, varius neque nec, mollis eros.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'15',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'60',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Máte dotaz?','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'800',
							'margin_top'=>'0',
							'margin_bottom'=>'25',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'html',
						'content'=>'<p><br><br>'.__('Zde vložte javascript kód pluginu pro vypsání komentářů, které chcete na stránce použít. Pro účely vysílání webináře je potřeba, aby bylo možné napsat komentář bez nutnosti znovunačtení stránky. Vhodné jsou například komentáře <a href="https://disqus.com" target="_blank">disqus</a>.','cms_ve').'<br><br></p>',
						'style'=>array(
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'13',
			),
			'border-top'=>array(
				'size'=>'2',
				'style'=>'solid',
				'color'=>'#ededed',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'60',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'like',
						'content'=>'',
						'style'=>array(
							'layout'=>'button_count',
							'scheme'=>'light',
							'setting'=>array(
								'share'=>'share',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
);

$config['layer']=base64_encode(serialize($temp_layer));

$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_color'=>'#ffffff') 
);
$config['config']=array(
  'styles'=>true,
);