<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Vytvořte si squeeze během minuty...','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Stáhněte si jednoduchý návod, jak si během chvilky vytvořit web, který bude opravdu prodávat.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'50',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'box',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'seform',
									'content'=>'',
									'style'=>array(
										'form-style'=>'1',
										'form-look'=>'2',
										'form-font'=>array(
											'font-size'=>'15',
											'color'=>'',
										),
										'background'=>'#eeeeee',
										'button_text'=>'',
										'button'=>array(
											'style'=>'3',
											'font'=>array(
												'font-size'=>'30',
												'font-family'=>'',
												'weight'=>'',
												'color'=>'#2b2b2b',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffde21',
												'color2'=>'#ffcc00',
											),
											'corner'=>'8',
											'border-color'=>'#d1a700',
										),
										'popup'=>'1',
										'popup_text'=>__('Stáhnout návod zdarma','cms_ve'),
										'popup_title'=>__('Zadejte svůj e-mail a stáhněte si návod zdarma.','cms_ve'),
										'popupbutton'=>array(
											'style'=>'3',
											'font'=>array(
												'font-size'=>'38',
												'font-family'=>'Open Sans',
												'weight'=>'600',
												'color'=>'#2b2b2b',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffde21',
												'color2'=>'#ffcc00',
											),
											'corner'=>'8',
											'border-color'=>'#d1a700',
										),
										'align'=>'center',
										'link_font'=>array(
											'font-size'=>'',
											'color'=>'',
										),
									),
									'config'=>array(
										'max_width'=>'100%',
										'margin_top'=>'0',
										'margin_bottom'=>'20',
										'delay'=>'',
										'class'=>'',
									),
								),
								'1'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">'.__('Vaše údaje jsou na 100 % v bezpečí.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'',
										),
										'li'=>'',
									),
									'config'=>array(
										'max_width'=>'',
										'margin_top'=>'0',
										'margin_bottom'=>'0',
										'delay'=>'',
										'class'=>'',
									),
								),
							),
						),
						'style'=>array(
							'background-color'=>'#eeeeee',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
              'padding'=>array(
								'top'=>'40',
								'bottom'=>'30',
								'left'=>'40',
								'right'=>'40',
							),
							'corner'=>'10',
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'link-color'=>'',
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;"><a href="" target="_blank">'.__('Obchodní podmínky','cms_ve').'</a></p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));

$config['setting']=array (  
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_color'=>'#ffffff') 
);

$config['config']=array(
  'styles'=>true,
);
