<?php 
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#e1ebed',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#3e6e7a',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'50',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'50',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'50',
				'unit'=>'px',
			),
			'type'=>'basic',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: left;">Lorem ipsum dolor sit amet consecte</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec varius sem vitae mauris aliquet.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('Zobrazit stránku','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'26',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'5',
								'border-color'=>'',
							),
							'align'=>'left',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>'',
							'click_action'=>'none',
							'alert'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
				),
			),
		),
	),
);

     
$config['setting']=array(
    've_popup'=>array(
        'width'=>array('size'=>'800','unit'=>'px'),
    )
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();