<?php
$content=array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#222222',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#aaaaaa',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'90',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Kontakt','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#ffffff',
								'color2'=>'',
								'transparency'=>'60',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. </p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'contactform',
						'content'=>'',
						'style'=>array(
							'email'=>'@',
							'button_text'=>__('Odeslat dotaz','cms_ve'),
							'hide'=>array(
								'is_saved'=>'1',
							),
							'form-appearance'=>'1',
							'form-style'=>'1',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#ffffff',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#158ebf',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.8',
								'width_padding'=>'1.2',
								'border-color'=>'',
								'hover_effect'=>'darker',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	);
