<?php
$content=array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#222222',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#aaaaaa',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Kontakt','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Sem patří podnadpis','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'mobile',
										'size'=>'46',
										'color'=>'#158ebf',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Telefon','cms_ve'),
									'text'=>'+420 465 456 456',
									'button_text'=>__('Více informací →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'pencil',
										'size'=>'39',
										'color'=>'#158ebf',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('E-mail','cms_ve'),
									'text'=>'email@email.cz',
									'button_text'=>__('Více informací →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'facebook',
										'size'=>'36',
										'color'=>'#158ebf',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Facebook','cms_ve'),
									'text'=>'www.facebook.com',
									'button_text'=>__('Více informací →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'three',
							'style'=>'1',
							'background-color'=>'#ffffff',
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'2',
								'font'=>array(
									'font-size'=>'13',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#737373',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'90',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_effect'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	);
