<?php
$content=array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'full',
			'padding_top'=>'0',
			'padding_bottom'=>'0',
			'padding_left'=>array(
				'size'=>'0',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'0',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'row_anchor'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image_gallery',
						'content'=>'',
						'style'=>array(
							'image_gallery_items'=>array(
								'0'=>MW_IMAGE_LIBRARY.'gallery/city.jpg',
								'1'=>MW_IMAGE_LIBRARY.'gallery/coffe_mug.jpg',
								'2'=>MW_IMAGE_LIBRARY.'gallery/man.jpeg',
								'3'=>MW_IMAGE_LIBRARY.'gallery/nature.jpeg',
								'4'=>MW_IMAGE_LIBRARY.'gallery/frenchfries.jpeg',
								'5'=>MW_IMAGE_LIBRARY.'gallery/woman-field.jpeg',
								'6'=>MW_IMAGE_LIBRARY.'gallery/smiling-child.jpeg',
								'7'=>MW_IMAGE_LIBRARY.'gallery/burger.jpeg',
							),
							'cols'=>'4',
							'cols_type'=>'full',
							'hover'=>'scale',
							'gallery_style'=>'no_captions',
							'thumb_name'=>'mio_columns_',
							'font'=>array(
								'font-size'=>'16',
								'font-family'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'animation'=>'fade',
							'delay'=>'3500',
							'speed'=>'1000',
							'color_scheme'=>'',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	);
