<?php
$content=array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'cover'=>'cover',
				'overlay_color'=>'#151d21',
				'overlay_transparency'=>'65',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'bg/restaurant_food.jpg',
				'imageid'=>'678',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'600',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
				),
			),
		),
);
