<?php
$content=array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#222222',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#aaaaaa',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'numbers',
						'content'=>'',
						'style'=>array(
							'numbers'=>array(
								'0'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'',
									),
									'number'=>'75',
									'unit'=>'',
									'title'=>__('Klientů','cms_ve'),
								),
								'1'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'31',
									),
									'number'=>'1245',
									'unit'=>'',
									'title'=>__('Fanoušků','cms_ve'),
								),
								'2'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'31',
									),
									'number'=>'3980',
									'unit'=>'',
									'title'=>__('Šálků kafe','cms_ve'),
								),
								'3'=>array(
									'type'=>'custom',
									'se'=>array(
										'api'=>'se',
										'id'=>'31',
									),
									'number'=>'15',
									'unit'=>'',
									'title'=>__('Let zkušeností','cms_ve'),
								),
							),
							'style'=>'1',
							'cols'=>'four',
							'number_font'=>array(
								'font-size'=>'55',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#ffffff',
							),
							'text_font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
						),
					),
				),
			),
		),
	);
