<?php
$content=array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#222222',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'',
				'overlay_transparency'=>'90',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#aaaaaa',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Ceník','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Sem patří podnadpis','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'pricelist',
						'content'=>'',
						'style'=>array(
							'pricelist'=>array(
								'0'=>array(
									'title'=>__('Základ','cms_ve'),
									'price'=>__('499 Kč','cms_ve'),
									'sale_price'=>'',
									'per'=>__('Ročně','cms_ve'),
									'features'=>array(
										'0'=>array(
											'text'=>'Lorem ipsum',
										),
										'1'=>array(
											'text'=>'Consectetur adipiscing',
										),
										'2'=>array(
											'text'=>'Dolor set amet',
										),
									),
									'button_text'=>__('Objednat','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, quam id dignissim sagittis.',
									'popular_text'=>__('NEJPRODÁVANĚJŠÍ','cms_ve'),
								),
								'1'=>array(
									'title'=>__('Profesional','cms_ve'),
									'price'=>__('999 Kč','cms_ve'),
									'sale_price'=>'',
									'per'=>__('Ročně','cms_ve'),
									'features'=>array(
										'0'=>array(
											'text'=>'Lorem ipsum',
										),
										'1'=>array(
											'text'=>'Consectetur adipiscing',
										),
										'2'=>array(
											'text'=>'Dolor set amet',
										),
									),
									'button_text'=>__('Objednat','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, quam id dignissim sagittis.',
									'popular'=>'1',
									'popular_text'=>__('NEJPRODÁVANĚJŠÍ','cms_ve'),
								),
								'2'=>array(
									'title'=>__('Enterprise','cms_ve'),
									'price'=>__('2999 Kč','cms_ve'),
									'sale_price'=>'',
									'per'=>__('Ročně','cms_ve'),
									'features'=>array(
										'0'=>array(
											'text'=>'Lorem ipsum',
										),
										'1'=>array(
											'text'=>'Consectetur adipiscing',
										),
										'2'=>array(
											'text'=>'Dolor set amet',
										),
									),
									'button_text'=>__('Objednat','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate, quam id dignissim sagittis.',
									'popular_text'=>__('NEJPRODÁVANĚJŠÍ','cms_ve'),
								),
							),
							'style'=>'1',
							'popular_color'=>'#158ebf',
							'background_color'=>'#333333',
							'text_color'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'20',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#158ebf',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.7',
								'width_padding'=>'1.3',
								'border-color'=>'',
								'hover_effect'=>'darker',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'font_title'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_features'=>array(
								'font-size'=>'',
								'line-height'=>'',
							),
							'font_description'=>array(
								'font-size'=>'',
								'line-height'=>'',
							),
						),
					),
				),
			),
		),
	);
