<?php
$slide1=array(
	'title' => __('Slide','cms_ve'),
	'theme' => 'mw_sliders/1/',
	'content' => array(
		'0'=>array(
				'type'=>'slide',
				'class'=>'',
				'style'=>array(
					'background_color'=>array(
						'color1'=>'',
						'color2'=>'',
						'transparency'=>'100',
					),
					'background_setting'=>'image',
					'background_image'=>array(
						'cover'=>'cover',
						'overlay_color'=>'#158ebf',
						'overlay_transparency'=>'80',
						'position'=>'center center',
						'repeat'=>'no-repeat',
						'image'=>MW_IMAGE_LIBRARY.'bg/forest2.jpeg',
						'imageid'=>'',
						'pattern'=>'',
					),
					'font'=>array(
						'font-size'=>'',
						'font-family'=>'',
						'weight'=>'',
						'color'=>'#ffffff',
					),
					'link_color'=>'',
				),
				'content'=>array(
					'0'=>array(
						'type'=>'col-two',
						'class'=>'',
						'content'=>array(
							'0'=>array(
								'type'=>'title',
								'content'=>'<p>'.__('Nadpis slidu','cms_ve').'</p>',
								'style'=>array(
									'font'=>array(
										'font-size'=>'55',
										'font-family'=>'',
										'weight'=>'',
										'line-height'=>'1.1',
										'color'=>'',
										'text-shadow'=>'none',
									),
									'style'=>'1',
									'border'=>array(
										'size'=>'1',
										'color'=>'#d5d5d5',
									),
									'background-color'=>array(
										'color1'=>'#efefef',
										'color2'=>'',
										'transparency'=>'100',
									),
									'decoration-color'=>'#158ebf',
									'align'=>'center',
								),
								'config'=>array(
									'max_width'=>'',
									'margin_top'=>'0',
									'margin_bottom'=>'20',
									'delay'=>'',
									'animate'=>'',
									'id'=>'',
									'class'=>'',
								),
							),
							'1'=>array(
								'type'=>'text',
								'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget arcu id lacus laoree. </p>',
								'style'=>array(
									'font'=>array(
										'font-size'=>'18',
										'font-family'=>'',
										'weight'=>'',
										'line-height'=>'',
										'color'=>'',
									),
									'li'=>'',
									'style'=>'1',
									'p-background-color'=>array(
										'color1'=>'#e8e8e8',
										'color2'=>'',
										'transparency'=>'100',
									),
								),
								'config'=>array(
									'max_width'=>'',
									'margin_top'=>'0',
									'margin_bottom'=>'40',
									'delay'=>'',
									'animate'=>'',
									'id'=>'',
									'class'=>'',
								),
							),
							'2'=>array(
								'type'=>'button',
								'content'=>__('Text tlačítka','cms_ve'),
								'style'=>array(
									'show'=>'url',
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
									'popup'=>'',
									'align'=>'left',
									'button'=>array(
										'style'=>'1',
										'font'=>array(
											'font-size'=>'18',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'#ffffff',
											'text-shadow'=>'none',
										),
										'background_color'=>array(
											'color1'=>'#d93d41',
											'color2'=>'',
										),
										'corner'=>'0',
										'height_padding'=>'1',
										'width_padding'=>'1.7',
										'border-color'=>'',
										'hover_effect'=>'darker',
										'hover_color'=>array(
											'color1'=>'',
											'color2'=>'',
										),
										'hover_font_color'=>'',
										'border_hover-color'=>'',
									),
									'text2'=>__('Text tlačítka','cms_ve'),
									'show2'=>'url',
									'link2'=>array(
										'page'=>'',
										'link'=>'',
									),
									'popup2'=>'',
									'button2'=>array(
										'style'=>'1',
										'font'=>array(
											'font-size'=>'30',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'#2b2b2b',
											'text-shadow'=>'none',
										),
										'background_color'=>array(
											'color1'=>'#ffde21',
											'color2'=>'#ffcc00',
										),
										'corner'=>'0',
										'height_padding'=>'0.5',
										'width_padding'=>'1.2',
										'border-color'=>'',
										'hover_effect'=>'lighter',
										'hover_color'=>array(
											'color1'=>'',
											'color2'=>'',
										),
										'hover_font_color'=>'',
										'border_hover-color'=>'',
									),
								),
							),
						),
					),
					'1'=>array(
						'type'=>'col-two',
						'class'=>'',
						'content'=>array(
						),
					),
				),
			)
	)
);

$slide2=array(
	'title' => __('Slide2','cms_ve'),
	'theme' => 'mw_sliders/1/',
	'content' => array(
		'0'=>array(
				'type'=>'slide',
				'class'=>'',
				'style'=>array(
					'background_color'=>array(
						'color1'=>'',
						'color2'=>'',
						'transparency'=>'100',
					),
					'background_setting'=>'image',
					'background_image'=>array(
						'cover'=>'cover',
						'overlay_color'=>'#158ebf',
						'overlay_transparency'=>'80',
						'position'=>'center center',
						'repeat'=>'no-repeat',
						'image'=>MW_IMAGE_LIBRARY.'bg/rocks.jpeg',
						'imageid'=>'',
						'pattern'=>'',
					),
					'font'=>array(
						'font-size'=>'',
						'font-family'=>'',
						'weight'=>'',
						'color'=>'#ffffff',
					),
					'link_color'=>'',
				),
				'content'=>array(
					'0'=>array(
						'type'=>'col-two',
						'class'=>'',
						'content'=>array(
							'0'=>array(
								'type'=>'title',
								'content'=>'<p>'.__('Další nadpis','cms_ve').'</p>',
								'style'=>array(
									'font'=>array(
										'font-size'=>'55',
										'font-family'=>'',
										'weight'=>'',
										'line-height'=>'1.1',
										'color'=>'',
										'text-shadow'=>'none',
									),
									'style'=>'1',
									'border'=>array(
										'size'=>'1',
										'color'=>'#d5d5d5',
									),
									'background-color'=>array(
										'color1'=>'#efefef',
										'color2'=>'',
										'transparency'=>'100',
									),
									'decoration-color'=>'#158ebf',
									'align'=>'center',
								),
								'config'=>array(
									'max_width'=>'',
									'margin_top'=>'0',
									'margin_bottom'=>'20',
									'delay'=>'',
									'animate'=>'',
									'id'=>'',
									'class'=>'',
								),
							),
							'1'=>array(
								'type'=>'text',
								'content'=>'<p>Cras nibh erat, fermentum ac justo sit amet, commodo aliquam metus. Integer sodales quis odio.</p>',
								'style'=>array(
									'font'=>array(
										'font-size'=>'18',
										'font-family'=>'',
										'weight'=>'',
										'line-height'=>'',
										'color'=>'',
									),
									'li'=>'',
									'style'=>'1',
									'p-background-color'=>array(
										'color1'=>'#e8e8e8',
										'color2'=>'',
										'transparency'=>'100',
									),
								),
								'config'=>array(
									'max_width'=>'',
									'margin_top'=>'0',
									'margin_bottom'=>'40',
									'delay'=>'',
									'animate'=>'',
									'id'=>'',
									'class'=>'',
								),
							),
							'2'=>array(
								'type'=>'button',
								'content'=>__('Text tlačítka','cms_ve'),
								'style'=>array(
									'show'=>'url',
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
									'popup'=>'',
									'align'=>'left',
									'button'=>array(
										'style'=>'1',
										'font'=>array(
											'font-size'=>'18',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'#ffffff',
											'text-shadow'=>'none',
										),
										'background_color'=>array(
											'color1'=>'#d93d41',
											'color2'=>'',
										),
										'corner'=>'0',
										'height_padding'=>'1',
										'width_padding'=>'1.7',
										'border-color'=>'',
										'hover_effect'=>'darker',
										'hover_color'=>array(
											'color1'=>'',
											'color2'=>'',
										),
										'hover_font_color'=>'',
										'border_hover-color'=>'',
									),
									'text2'=>__('Text tlačítka','cms_ve'),
									'show2'=>'url',
									'link2'=>array(
										'page'=>'',
										'link'=>'',
									),
									'popup2'=>'',
									'button2'=>array(
										'style'=>'1',
										'font'=>array(
											'font-size'=>'30',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'#2b2b2b',
											'text-shadow'=>'none',
										),
										'background_color'=>array(
											'color1'=>'#ffde21',
											'color2'=>'#ffcc00',
										),
										'corner'=>'0',
										'height_padding'=>'0.5',
										'width_padding'=>'1.2',
										'border-color'=>'',
										'hover_effect'=>'lighter',
										'hover_color'=>array(
											'color1'=>'',
											'color2'=>'',
										),
										'hover_font_color'=>'',
										'border_hover-color'=>'',
									),
								),
							),
						),
					),
					'1'=>array(
						'type'=>'col-two',
						'class'=>'',
						'content'=>array(
						),
					),
				),
			)
	)
);


$content=array(
		'type'=>'slider',
		'class'=>'',
		'style'=>array(
			'slides'=>array(
				'0'=>array(
					'slider_content'=>$slide1,
				),
				'1'=>array(
					'slider_content'=>$slide2,
				),
			),
			'slider_height'=>'',
			'animation'=>'fade',
			'a_delay'=>'5000',
			'speed'=>'1000',
			'color_scheme'=>'light',
			'delay'=>'',
		),
);
