<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#000000',
				'overlay_transparency'=>'57',
				'position'=>'center center',
				'repeat'=>'repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Ručně vyráběné šperky','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'70',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.1',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies nibh nec ante pretium, et lacinia turpis blandit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'120',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'catalog',
						'content'=>'',
						'style'=>array(
							'item_type'=>'own',
							'items'=>array(
								'0'=>array(
									'title'=>__('Název produktu','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/earrings1.jpg',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'350 '.__('Kč','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>__('Název produktu','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/earrings2.jpg',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'350 '.__('Kč','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>__('Název produktu','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/earrings3.jpg',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'350 '.__('Kč','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'3'=>array(
									'title'=>__('Název produktu','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/earrings4.jpg',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'350 '.__('Kč','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'4'=>array(
									'title'=>__('Název produktu','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/earrings5.jpg',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'350 '.__('Kč','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'5'=>array(
									'title'=>__('Název produktu','cms_ve'),
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/earrings6.jpg',
										'imageid'=>'',
									),
									'subtitle'=>'',
									'description'=>'',
									'price'=>'350 '.__('Kč','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'page'=>'',
							'cols'=>'3',
							'style'=>'4',
							'text_align'=>'center',
							'font_title'=>array(
								'font-size'=>'25',
							),
							'font_description'=>array(
								'font-size'=>'',
							),
							'font_color'=>'',
							'font_price'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'animation'=>'fade',
							'delay'=>'3500',
							'speed'=>'1000',
							'color_scheme'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Chcete šperk na míru?','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'45',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies nibh nec ante pretium, et lacinia turpis blandit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'45',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('Chci šperk na míru','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'18',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#d6521e',
									'color2'=>'',
								),
								'corner'=>'84',
								'height_padding'=>'0.9',
								'width_padding'=>'1.6',
								'border-color'=>'#ffffff',
								'hover_effect'=>'darker',
								'hover_color'=>array(
									'color1'=>'#c90a30',
									'color2'=>'',
								),
								'hover_font_color'=>'#ffffff',
								'border_hover-color'=>'#c90a30',
							),
							'text2'=>__('Chci šperk na míru','cms_ve'),
							'show2'=>'url',
							'link2'=>array(
								'page'=>'',
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'18',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'84',
								'height_padding'=>'0.8',
								'width_padding'=>'1.6',
								'border-color'=>'#ffffff',
								'hover_effect'=>'darker',
								'hover_color'=>array(
									'color1'=>'#c90a30',
									'color2'=>'',
								),
								'hover_font_color'=>'#ffffff',
								'border_hover-color'=>'#c90a30',
							),
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Šperky','cms_ve'),   
      'slug' => __('sperky','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
