<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#151d21',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'cover'=>'cover',
				'color_filter'=>'color_filter',
				'overlay_color'=>'#1d1e21',
				'overlay_transparency'=>'70',
				'position'=>'left top',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'bg/town1.jpg',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#ffffff',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Máme 20 let praxe','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'59',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.1',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing <br />elit nec ipsum nec ligula.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'',
				'overlay_transparency'=>'90',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#f7f7f7',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h2 style="text-align: center;">'.__('Náš tým','cms_ve').'</h2>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'15',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">'.__('Sem patří podnadpis','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'#7a7979',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'peoples',
						'content'=>'',
						'style'=>array(
							'peoples'=>array(
								'0'=>array(
									'title'=>__('Jméno Příjmení','cms_ve'),
									'position'=>__('Pozice','cms_ve'),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/face-w.jpg',
										'imageid'=>'',
									),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'1'=>array(
									'title'=>__('Jméno Příjmení','cms_ve'),
									'position'=>__('Pozice','cms_ve'),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
										'imageid'=>'',
									),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
								'2'=>array(
									'title'=>__('Jméno Příjmení','cms_ve'),
									'position'=>__('Pozice','cms_ve'),
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vulputate.',
									'image'=>array(
										'image'=>MW_IMAGE_LIBRARY.'misc/face-w2.jpg',
										'imageid'=>'',
									),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'three',
							'style'=>'2',
							'font'=>array(
								'font-size'=>'24',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_position'=>array(
								'font-size'=>'14',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#888888',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'animation'=>'fade',
							'delay'=>'3500',
							'speed'=>'1000',
							'color_scheme'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('O nás','cms_ve'),   
      'slug' => __('o-nas','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
