<?php 
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#262626',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#a8a8a8',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-four',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Menu 1','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'14',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'menu',
						'content'=>'',
						'style'=>array(
							'type'=>'menu',
							'menu'=>'',
							'page'=>'',
							'title'=>'',
							'style'=>'8',
							'font'=>array(
								'font-size'=>'13',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#a8a8a8',
							),
							'color-active'=>'#fff',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-four',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Menu 2','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'14',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'menu',
						'content'=>'',
						'style'=>array(
							'type'=>'menu',
							'menu'=>'',
							'page'=>'',
							'title'=>'',
							'style'=>'8',
							'font'=>array(
								'font-size'=>'13',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#a8a8a8',
							),
							'color-active'=>'#fff',
						),
					),
				),
			),
			'2'=>array(
				'type'=>'col-four',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Menu 3','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'14',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'menu',
						'content'=>'',
						'style'=>array(
							'type'=>'menu',
							'menu'=>'',
							'page'=>'',
							'title'=>'',
							'style'=>'8',
							'font'=>array(
								'font-size'=>'13',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#a8a8a8',
							),
							'color-active'=>'#fff',
						),
					),
				),
			),
			'3'=>array(
				'type'=>'col-four',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p>Lorem ipsum dolor</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'14',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'10',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
					'2'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'type'=>'custom',
							'html'=>'',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'1',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'26',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup'=>'1',
							'popup_title'=>__('Zadejte svůj e-mail a registrujte se.','cms_ve'),
							'popup_type'=>'button',
							'image'=>'',
							'popup_text'=>__('Registrovat se','cms_ve'),
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'16',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'left',
						),
					),
				),
			),
		),
	),
);

     
$config['setting']=array();
$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();