<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#021830',
				'color2'=>'',
				'transparency'=>'87',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'cover'=>'cover',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'40',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'full_height'=>'full_height',
				'noheader'=>'noheader',
				'centered_content'=>'centered_content',
			),
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('JANA NOVÁKOVÁ','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'90',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'0',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('MISTRYNĚ OSOBNÍHO ROZVOJE','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'Open Sans',
								'weight'=>'300',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('NAJMOUT SI MĚ','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'4',
								'font'=>array(
									'font-size'=>'22',
									'font-family'=>'Open Sans',
									'weight'=>'700',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.9',
								'width_padding'=>'2.3',
								'border-color'=>'#ffffff',
								'hover_color'=>array(
									'color1'=>'#ffffff',
									'color2'=>'',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'#2b2b2b',
								'border_hover-color'=>'',
							),
							'text2'=>'Text tlačítka',
							'show2'=>'url',
							'link2'=>array(
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'90',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'videocam-1',
										'size'=>'50',
										'color'=>'#1c364d',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'ETIAM EUISMOD PURUS',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
									'link'=>array(
										'link'=>'',
									),
								),
								'1'=>array(
									'icon'=>array(
										'icon'=>'camera',
										'size'=>'50',
										'color'=>'#1c364d',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'ETIAM EUISMOD PURUS',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
									'link'=>array(
										'link'=>'',
									),
								),
								'2'=>array(
									'icon'=>array(
										'icon'=>'heart-1',
										'size'=>'50',
										'color'=>'#1c364d',
										'image'=>'',
										'tab'=>'icon',
									),
									'title'=>'ETIAM EUISMOD PURUS',
									'text'=>'Suspendisse quis scelerisque nulla. Etiam euismod purus eu dictum porta. In mollis facilisis ante, vitae vulputate leo. Sed consectetur hendrerit quam quis mattis. ',
									'link'=>array(
										'link'=>'',
									),
								),
							),
							'cols'=>'three',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'2',
								'font'=>array(
									'font-size'=>'13',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#737373',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'90',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#021830',
				'color2'=>'',
				'transparency'=>'87',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#c8d4d9',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('REFERENCE','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'37',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'testimonials',
						'content'=>'',
						'style'=>array(
							'testimonials'=>array(
								'0'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Petra','cms_ve'),
									'company'=>__('Finanční poradce','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-w.jpg',
								),
								'1'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
                  'name'=>__('Honza','cms_ve'),
									'company'=>__('Informatik','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-m.jpg',
								),
								'2'=>array(
									'text'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque velit a dolor fermentum, eget viverra risus finibus. Nam libero quam, imperdiet at magna vel, tincidunt elementum blandit quam tincidunt sem. ',
									'name'=>__('Jana','cms_ve'),
									'company'=>__('Účetní','cms_ve'),
									'image'=>MW_IMAGE_LIBRARY.'misc/face-w2.jpg',
								),
							),
							'cols'=>'three',
							'style'=>'7',
							'font'=>array(
								'font-size'=>'15',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font-author'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
							),
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'90',
			'padding_bottom'=>'90',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'css_class'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('NĚCO MÁLO O MNĚ','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam. Donec pretium nisl dolor, at finibus nisi ultricies et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet suscipit ex, at convallis libero. Aliquam erat volutpat. Aenean interdum augue eros, a commodo arcu imperdiet aliquam.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'45',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'button',
						'content'=>__('Více o mně','cms_ve'),
						'style'=>array(
							'show'=>'url',
							'link'=>array(
								'link'=>'',
							),
							'popup'=>'',
							'align'=>'center',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'19',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#1c364d',
									'color2'=>'',
								),
								'corner'=>'0',
								'height_padding'=>'0.7',
								'width_padding'=>'1.4',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'#224f7a',
									'color2'=>'',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
							'show2'=>'url',
							'link2'=>array(
								'link'=>'',
							),
							'popup2'=>'',
							'button2'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'corner'=>'0',
								'height_padding'=>'0.5',
								'width_padding'=>'1.2',
								'border-color'=>'',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'hover_effect'=>'',
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
				),
			),
		),
	),
);$config['setting']=array ( 
	've_header' => array(
		'show'=>'noheader',
		'appearance'=>'type11',
		'logo'=>'',
		'before_header'=>'',
		'background_color'=>array(
			'color1'=>'#181c26',
			'color2'=>'',
			'transparency'=>'100',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
		),
		'menu'=>'55',
		'menu_font'=>array(
			'font-size'=>'15',
			'font-family'=>'Open Sans',
			'weight'=>'700',
			'color'=>'#7f8491',
		),
		'menu_active_color'=>'#ffffff',
		'menu_submenu_text_color'=>'#ffffff',
		'menu_bg'=>array(
			'color1'=>'#121212',
			'color2'=>'',
		),
		'header_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
		'header_padding'=>'10',
		'background_color_fix'=>array(
			'color1'=>'',
			'color2'=>'',
			'transparency'=>'100',
		),
		'header_padding_fix'=>array(
			'size'=>'',
		),
	),

	've_footer' => array(
		'show'=>'page',
		'custom_footer'=>'',
		'appearance'=>'type2',
		'text'=>'',
		'menu'=>'',
		'background_color'=>array(
			'color1'=>'#021830',
			'color2'=>'',
			'transparency'=>'87',
		),
		'background_image'=>array(
			'position'=>'center center',
			'repeat'=>'no-repeat',
			'image'=>'',
		),
		'font'=>array(
			'font-size'=>'13',
			'font-family'=>'',
			'weight'=>'',
			'color'=>'#b3bdc2',
		),
		'footer_width'=>array(
			'size'=>'',
			'unit'=>'px',
		),
	),
 
);


$config['setting']=array ( 
 've_header' => array('show' => 'noheader'),
 've_footer' => array('show' => 'page', 'appearance'=>'type2', 'background_color'=>array('color1'=>'#021830','color2'=>'','transparency'=>'87'),'font'=>array('font-family'=>'','weight'=>'','color'=>'#b3bdc2')), 
 've_appearance' => array('background_image'=>array('position'=>'center center','repeat'=>'no-repeat','cover'=>'cover','fixed'=>'fixed','image'=>'http://servis.mioweb.cz/graphic/bg/personal1.jpg','pattern'=>'0',))
);

$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();
