<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#007ab3',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'30',
			'padding_bottom'=>'20',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Kontaktujte nás','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'35',
								'font-family'=>'Open Sans',
								'weight'=>'700',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'normal',
								'color'=>'#c4d8e6',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'13',
							'delay'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#fff',
				'color2'=>'',
			),
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Kontaktní formulář','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
					),
					'1'=>array(
						'type'=>'contactform',
						'content'=>'',
						'style'=>array(
							'email'=>'@',
							'button_text'=>__('Odeslat dotaz','cms_ve'),
							'form-style'=>'2',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'25',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#0c89c7',
									'color2'=>'#007ab3',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>__('Název firmy','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'25',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>__('Adresa a další údaje','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'title',
						'content'=>__('Korespondenční adresa','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
					),
					'3'=>array(
						'type'=>'text',
						'content'=>__('Korespondenční adresa','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'35',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'4'=>array(
						'type'=>'title',
						'content'=>__('E-mail','cms_ve'),
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
					),
					'5'=>array(
						'type'=>'text',
						'content'=>'<p>email@email.cz</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array();
$config['config']=array();
