<?php 
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'1',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'type'=>'basic',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur elit.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'40',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'30',
							'delay'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'10',
			'padding_bottom'=>'40',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'type'=>'basic',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>'',
							'click_action'=>'none',
							'alert'=>'',
							'link'=>array(
								'link'=>'',
							),
							'large_image'=>'',
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: left;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam lacinia cursus nisl, vel dictum enim.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'16',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
						),
					),
					'1'=>array(
						'type'=>'seform',
						'content'=>'',
						'style'=>array(
							'type'=>'custom',
							'email'=>'',
							'subject'=>'',
							'thx_url'=>'',
							'form-style'=>'1',
							'form-labels'=>'1',
							'form-look'=>'2',
							'form-font'=>array(
								'font-size'=>'15',
								'color'=>'',
							),
							'background'=>'#eeeeee',
							'button_text'=>'',
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'23',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#219ed1',
									'color2'=>'#007ea6',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'0',
								'border-color'=>'',
							),
							'popup_type'=>'button',
							'image'=>'',
							'popupbutton'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'30',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#2b2b2b',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#ffde21',
									'color2'=>'#ffcc00',
								),
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'',
								),
								'corner'=>'8',
								'border-color'=>'',
							),
							'link_font'=>array(
								'font-size'=>'',
								'color'=>'',
							),
							'align'=>'center',
						),
					),
				),
			),
		),
	),
);


     
$config['setting']=array(
    've_popup'=>array(
        'width'=>array('size'=>'700','unit'=>'px'),
    )
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['config']=array();