<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'',
				'overlay_transparency'=>'90',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#d8e3e8',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'100',
			'padding_bottom'=>'100',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: center;">'.__('Naše služby','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'decoration-color'=>'#158ebf',
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'18',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'600',
							'margin_top'=>'0',
							'margin_bottom'=>'45',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'search-1',
										'size'=>'35',
										'color'=>'#1d9fe0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Název služby','cms_ve'),
									'text'=>'',
									'button_text'=>__('Více informací →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'14',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#b8b8b8',
									'color2'=>'',
								),
								'corner'=>'49',
								'height_padding'=>'0.6',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'2'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#f0f0f0',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'params',
										'size'=>'35',
										'color'=>'#1d9fe0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Název služby','cms_ve'),
									'text'=>'',
									'button_text'=>__('Více informací →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'14',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#b8b8b8',
									'color2'=>'',
								),
								'corner'=>'49',
								'height_padding'=>'0.6',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'3'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_setting'=>'image',
			'background_image'=>array(
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'background_delay'=>'3000',
			'background_speed'=>'1500',
			'background_video_mp4'=>'',
			'background_video_webm'=>'',
			'background_video_ogg'=>'',
			'video_setting'=>array(
				'is_saved'=>'1',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'height_setting'=>array(
				'arrow_color'=>'#fff',
			),
			'min-height'=>'',
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'features',
						'content'=>'',
						'style'=>array(
							'features'=>array(
								'0'=>array(
									'icon'=>array(
										'icon'=>'key',
										'size'=>'35',
										'color'=>'#1d9fe0',
										'image'=>array(
											'image'=>'',
											'imageid'=>'',
										),
										'tab'=>'icon',
									),
									'title'=>__('Název služby','cms_ve'),
									'text'=>'',
									'button_text'=>__('Více informací →','cms_ve'),
									'link'=>array(
										'page'=>'',
										'link'=>'',
									),
								),
							),
							'cols'=>'one',
							'style'=>'1',
							'background-color'=>'#209ccf',
							'font'=>array(
								'font-size'=>'30',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'font_text'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'button'=>array(
								'style'=>'1',
								'font'=>array(
									'font-size'=>'14',
									'font-family'=>'',
									'weight'=>'',
									'color'=>'#ffffff',
									'text-shadow'=>'none',
								),
								'background_color'=>array(
									'color1'=>'#b8b8b8',
									'color2'=>'',
								),
								'corner'=>'49',
								'height_padding'=>'0.6',
								'width_padding'=>'1.2',
								'border-color'=>'#bdbdbd',
								'hover_effect'=>'lighter',
								'hover_color'=>array(
									'color1'=>'',
									'color2'=>'#ebebeb',
								),
								'hover_font_color'=>'',
								'border_hover-color'=>'',
							),
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam efficitur nisl, ac ullamcorper justo dictum vel. Phasellus maximus elementum cursus. Vestibulum vel fermentum lectus. Integer finibus nibh nec quam imperdiet iaculis. Vivamus tempus dui eu nisi facilisis vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc nec tristique diam.</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.7',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Naše služby','cms_ve'),   
      'slug' => __('nase-sluzby','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
