<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'#a8a8a8',
			),
			'link_color'=>'',
			'background_color'=>array(
				'color1'=>'',
				'color2'=>'',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'pattern'=>'0',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'padding_top'=>'40',
			'padding_bottom'=>'40',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-one',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<p style="text-align: center;">'.__('Připravujeme nový web a již brzy ho pro vás spustíme.','cms_ve').'</p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'44',
								'font-family'=>'',
								'weight'=>'',
								'color'=>'#ffffff',
								'text-shadow'=>'none',
							),
						),
						'config'=>array(
							'max_width'=>'700',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'countdown',
						'content'=>array(
							'date'=>'00000',
							'hour'=>'0',
							'minute'=>'0',
						),
						'style'=>array(
							'style'=>'3',
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
							),
							'background-color'=>'#212121',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'50',
							'margin_bottom'=>'50',
							'delay'=>'',
							'class'=>'',
						),
					),
					'2'=>array(
						'type'=>'box',
						'content'=>array(
							'0'=>array(
								'0'=>array(
									'type'=>'text',
									'content'=>'<p style="text-align: center;">'.__('Chcete být mezi prvními, kdo se o spuštění dozví? Vyplňte formulář níže a my vám dáme vědět.','cms_ve').'</p>',
									'style'=>array(
										'font'=>array(
											'font-size'=>'16',
											'font-family'=>'',
											'weight'=>'',
											'color'=>'',
										),
										'li'=>'',
									),
									'config'=>array(
										'max_width'=>'500',
										'margin_top'=>'0',
										'margin_bottom'=>'40',
										'delay'=>'',
										'class'=>'',
									),
								),
								'1'=>array(
									'type'=>'seform',
									'content'=>'',
									'style'=>array(
										'form-style'=>'2',
										'form-look'=>'5',
										'form-font'=>array(
											'font-size'=>'18',
											'color'=>'',
										),
										'background'=>'#ffffff',
										'button_text'=>'',
										'button'=>array(
											'style'=>'6',
											'font'=>array(
												'font-size'=>'25',
												'font-family'=>'Open Sans',
												'weight'=>'600',
												'color'=>'#ffffff',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#c20e0e',
												'color2'=>'#9e0c0c',
											),
											'corner'=>'0',
											'border-color'=>'',
										),
										'popupbutton'=>array(
											'style'=>'1',
											'font'=>array(
												'font-size'=>'30',
												'font-family'=>'',
												'weight'=>'',
												'color'=>'#2b2b2b',
												'text-shadow'=>'none',
											),
											'background_color'=>array(
												'color1'=>'#ffde21',
												'color2'=>'#ffcc00',
											),
											'corner'=>'8',
											'border-color'=>'',
										),
										'link_font'=>array(
											'font-size'=>'',
											'color'=>'',
										),
									),
								),
							),
						),
						'style'=>array(
							'background_color'=>array(
								'color1'=>'#212121',
								'color2'=>'',
								'transparency'=>'100',
							),
							'background_image'=>array(
								'position'=>'center center',
								'repeat'=>'no-repeat',
								'image'=>'',
								'imageid'=>'',
								'pattern'=>'',
							),
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'link-color'=>'',
							'border'=>array(
								'size'=>'0',
								'color'=>'',
							),
							'corner'=>'10',
							'padding'=>array(
								'top'=>'40',
								'bottom'=>'30',
								'left'=>'40',
								'right'=>'40',
							),
							'box-shadow'=>array(
								'horizontal'=>'0',
								'vertical'=>'0',
								'size'=>'0',
								'transparency'=>'10',
							),
							'title'=>'',
							'title-font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'align'=>'center',
								'color'=>'',
							),
							'title_bg'=>array(
								'color1'=>'#eeeeee',
								'color2'=>'',
								'transparency'=>'100',
							),
							'title_border'=>array(
								'size'=>'0',
								'color'=>'',
							),
						),
						'config'=>array(
							'max_width'=>'520',
							'margin_top'=>'0',
							'margin_bottom'=>'20',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
);
$config['layer']=base64_encode(serialize($temp_layer));
$config['setting']=array (  
 've_header' => array('show' => 'page', 'appearance'=>'type11', 'logo' =>  get_template_url_image().'/modules/visualeditor/images/default/logo2.png', 'background_color'=>array('color1'=>'','color2'=>''), 'menu_font'=>array('font-family'=>''), 'menu'=>''),
 've_footer' => array('show' => 'nofooter'), 
 've_appearance' => array('background_image' => array('pattern' => '9', 'image' =>  ''),'background_color'=>'#3d3d3d') 
);
$config['config']=array();