<?php
$temp_layer=array(
	'0'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#efefef',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'cover'=>'cover',
				'overlay_color'=>'#158ebf',
				'overlay_transparency'=>'80',
				'position'=>'left top',
				'repeat'=>'no-repeat',
				'image'=>MW_IMAGE_LIBRARY.'webs/reality/woman2.jpg',
				'imageid'=>'22',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'140',
			'padding_bottom'=>'140',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
				),
			),
			'1'=>array(
				'type'=>'col-two',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'title',
						'content'=>'<h1 style="text-align: left;">'.__('Můj příběh','cms_ve').'</h1>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'50',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.2',
								'color'=>'',
								'text-shadow'=>'none',
							),
							'style'=>'1',
							'border'=>array(
								'size'=>'1',
								'color'=>'#d5d5d5',
							),
							'background-color'=>array(
								'color1'=>'#efefef',
								'color2'=>'',
								'transparency'=>'100',
							),
							'align'=>'center',
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'40',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
					'1'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis nibh consequat, feugiat urna et, consectetur justo. Suspendisse potenti. Vivamus feugiat, nunc ut elementum hendrerit, nunc ex finibus augue, eu venenatis nunc orci id augue. Nulla tempor erat urna, id dignissim enim congue at. Etiam dapibus interdum odio a gravida. Donec risus purus, pellentesque a lacus vel, imperdiet mollis augue. </p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'20',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
						'config'=>array(
							'max_width'=>'',
							'margin_top'=>'0',
							'margin_bottom'=>'60',
							'delay'=>'',
							'animate'=>'',
							'id'=>'',
							'class'=>'',
						),
					),
				),
			),
		),
	),
	'1'=>array(
		'class'=>'',
		'style'=>array(
			'background_color'=>array(
				'color1'=>'#ffffff',
				'color2'=>'',
				'transparency'=>'100',
			),
			'background_image'=>array(
				'position'=>'center center',
				'repeat'=>'no-repeat',
				'image'=>'',
				'imageid'=>'',
				'pattern'=>'',
			),
			'font'=>array(
				'font-size'=>'',
				'font-family'=>'',
				'weight'=>'',
				'color'=>'',
			),
			'link_color'=>'',
			'type'=>'basic',
			'padding_top'=>'80',
			'padding_bottom'=>'80',
			'padding_left'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'padding_right'=>array(
				'size'=>'',
				'unit'=>'px',
			),
			'margin_t'=>array(
				'size'=>'',
			),
			'margin_b'=>array(
				'size'=>'',
			),
			'border-top'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'border-bottom'=>array(
				'size'=>'0',
				'style'=>'solid',
				'color'=>'',
			),
			'min-height'=>'',
			'height_setting'=>array(
				'is_saved'=>'1',
			),
			'css_class'=>'',
			'delay'=>'',
		),
		'content'=>array(
			'0'=>array(
				'type'=>'col-twothree',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'text',
						'content'=>'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis nibh felis, id tincidunt mauris semper et. Curabitur vitae efficitur ipsum. Praesent dapibus, tellus a fringilla pellentesque, augue nisi sollicitudin arcu, ac consequat erat neque in leo. Nunc leo justo, feugiat at luctus in, interdum in velit. Etiam lobortis sed quam id varius. Mauris nec augue laoreet, auctor dolor non, suscipit sem. Cras ac dui sit amet neque consequat pretium. Nulla est urna, ultricies ut ornare quis, ultrices sodales augue. Ut eu iaculis arcu. Maecenas ac pharetra lacus. Ut lacus lectus, maximus in lectus eget, eleifend auctor sapien. Maecenas sit amet erat at ipsum efficitur efficitur. Curabitur erat purus, porta non tempus a, eleifend vestibulum nisl. Nullam a leo ante. Pellentesque sed venenatis eros, condimentum accumsan justo. Fusce ullamcorper facilisis odio, pulvinar tincidunt ligula.</p>
<p>Suspendisse aliquam et leo tempor scelerisque. Sed tincidunt bibendum tortor vitae consequat. Praesent in convallis mauris. Fusce ut efficitur neque. Etiam dapibus lacus nec dolor egestas, a varius lorem sollicitudin. Suspendisse potenti. Fusce quis risus est. Sed volutpat facilisis enim vitae volutpat. Praesent dictum magna eget varius pulvinar. Maecenas id fringilla felis. Cras vitae fringilla leo. Nullam fermentum ex urna, ut facilisis eros ullamcorper ac.</p>
<p>Maecenas vehicula rhoncus orci. Nullam blandit ultricies enim ut convallis. Mauris vestibulum facilisis risus a ultrices. Phasellus felis nisl, rhoncus in leo facilisis, pretium efficitur mauris. Donec in turpis eu justo congue sollicitudin venenatis eu eros. Suspendisse vestibulum purus quis dictum elementum. Sed efficitur felis vitae dolor ullamcorper vehicula. Donec vestibulum at est vel pellentesque. Nulla molestie metus felis, quis fringilla lorem feugiat eu. Donec quis commodo purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur scelerisque lorem lorem, sed tristique sem imperdiet in. Nam sed fringilla mi, non accumsan nulla. Donec pellentesque massa vel fermentum condimentum. Quisque vitae purus vitae dui bibendum cursus suscipit non leo.</p></p>',
						'style'=>array(
							'font'=>array(
								'font-size'=>'',
								'font-family'=>'',
								'weight'=>'',
								'line-height'=>'1.6',
								'color'=>'',
							),
							'li'=>'',
							'style'=>'1',
							'p-background-color'=>array(
								'color1'=>'#e8e8e8',
								'color2'=>'',
								'transparency'=>'100',
							),
						),
					),
				),
			),
			'1'=>array(
				'type'=>'col-three',
				'class'=>'',
				'content'=>array(
					'0'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'webs/reality/woman3.jpg',
								'imageid'=>'45',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
					'1'=>array(
						'type'=>'image',
						'content'=>'',
						'style'=>array(
							'image'=>array(
								'image'=>MW_IMAGE_LIBRARY.'webs/reality/woman4.jpg',
								'imageid'=>'44',
							),
							'click_action'=>'none',
							'alert'=>'',
							'popup'=>'',
							'link'=>array(
								'page'=>'',
								'link'=>'',
							),
							'large_image'=>array(
								'image'=>'',
								'imageid'=>'',
							),
							'align'=>'center',
							'max-width'=>'',
							'label'=>'',
							'style'=>'1',
						),
					),
				),
			),
		),
	),
);
$page=array(
  'page'=>array(      
      'title' => __('Můj příběh','cms_ve'),   
      'slug' => __('muj-pribeh','cms_ve'), 
      'theme' => 'page/1/',
  ),
  'setting'=>array (),
  'layer'=>base64_encode(serialize($temp_layer)),
);
